# Generated by Django 6.1.1 on 2026-09-07 01:52

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('prefix', models.CharField(blank=True, max_length=12)),
                ('include_year', models.BooleanField(default=True)),
                ('width', models.PositiveSmallIntegerField(default=5)),
                ('separator', models.CharField(default='/', max_length=2)),
                ('next_value', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_number', models.CharField(editable=False, max_length=40, unique=True)),
                ('family_name', models.CharField(max_length=100)),
                ('given_name', models.CharField(max_length=100)),
                ('other_names', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_birth_is_estimated', models.BooleanField(default=False, help_text='True where the patient does not know an exact date of birth.')),
                ('sex', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other'), ('unknown', 'Unknown')], max_length=10)),
                ('phone_primary', models.CharField(blank=True, db_index=True, max_length=30)),
                ('phone_alternate', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address_line', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Nigeria', max_length=100)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('genotype', models.CharField(blank=True, choices=[('AA', 'AA'), ('AS', 'AS'), ('AC', 'AC'), ('SS', 'SS'), ('SC', 'SC'), ('CC', 'CC')], max_length=2)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deceased', 'Deceased'), ('merged', 'Merged into another record')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('search_name', models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Trim(django.db.models.functions.text.Concat('given_name', models.Value(' '), 'other_names', models.Value(' '), 'family_name')), output_field=models.TextField())),
                ('facility', models.ForeignKey(help_text='Where the patient was registered.', on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='facilities.facility')),
                ('merged_into', models.ForeignKey(blank=True, help_text='Set when this record was merged away. The record itself is kept.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merged_from', to='patients.patient')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patients_registered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['family_name', 'given_name'],
            },
        ),
        migrations.CreateModel(
            name='NextOfKin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('relationship', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('is_emergency_contact', models.BooleanField(default=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_of_kin', to='patients.patient')),
            ],
            options={
                'verbose_name_plural': 'next of kin',
            },
        ),
        migrations.CreateModel(
            name='PatientAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_system', models.CharField(blank=True, help_text='e.g. ICD-10, LOINC, ATC', max_length=64)),
                ('code', models.CharField(blank=True, max_length=64)),
                ('code_display', models.CharField(blank=True, max_length=255)),
                ('code_version', models.CharField(blank=True, help_text='Release of the code system used.', max_length=32)),
                ('substance', models.CharField(max_length=200)),
                ('reaction', models.CharField(blank=True, max_length=255)),
                ('severity', models.CharField(blank=True, choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='patients.patient')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'patient allergies',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientChronicCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_system', models.CharField(blank=True, help_text='e.g. ICD-10, LOINC, ATC', max_length=64)),
                ('code', models.CharField(blank=True, max_length=64)),
                ('code_display', models.CharField(blank=True, max_length=255)),
                ('code_version', models.CharField(blank=True, help_text='Release of the code system used.', max_length=32)),
                ('condition', models.CharField(max_length=200)),
                ('noted_on', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chronic_conditions', to='patients.patient')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['family_name', 'given_name'], name='patients_pa_family__a96a9c_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['date_of_birth'], name='patients_pa_date_of_4302f5_idx'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.CheckConstraint(condition=models.Q(('merged_into__isnull', True), ('status', 'merged'), _connector='OR'), name='merged_patient_has_merged_status'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.CheckConstraint(condition=models.Q(('merged_into', models.F('id')), _negated=True), name='patient_not_merged_into_itself'),
        ),
    ]
