# Generated by Django 6.1.1 on 2026-09-07 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_trigram_search'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['family_name', 'given_name'], 'permissions': [('merge_patient', 'Can merge duplicate patient records'), ('register_duplicate_patient', 'Can register a patient despite a suspected duplicate'), ('view_patient_access_log', 'Can see who has accessed a patient record')]},
        ),
    ]
