# Generated by Django 6.1.1 on 2026-09-07 02:00

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
        ('patients', '0003_alter_patient_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='patient',
            index=django.contrib.postgres.indexes.GinIndex(fields=['phone_primary'], name='patient_phone_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
