# Generated by Django 6.1.1 on 2026-09-10 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_patient_phone_trgm'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_unidentified',
            field=models.BooleanField(default=False, help_text='Registered before the patient could be identified.'),
        ),
    ]
