# Generated by Django 6.1.1 on 2026-09-07 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='discount_limit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Largest discount this role may apply without approval.', max_digits=12),
        ),
    ]
