# Generated by Django 6.1.1 on 2026-09-10 05:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], max_length=10)),
                ('to_address', models.CharField(help_text='A phone number or an email address.', max_length=200)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField()),
                ('source_type', models.CharField(blank=True, max_length=60)),
                ('source_id', models.CharField(blank=True, max_length=64)),
                ('patient_reference', models.CharField(blank=True, help_text='Hospital number, for tracing. Never clinical detail.', max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Waiting to send'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('next_attempt_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('provider_reference', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_messages', to='facilities.facility')),
            ],
            options={
                'ordering': ['next_attempt_at', 'id'],
                'permissions': [('view_outbox', 'Can see the outbound message queue'), ('retry_outbound_message', 'Can put a failed message back in the queue')],
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='notificatio_status_431eed_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('body', ''), _negated=True), name='outbound_message_has_a_body'), models.CheckConstraint(condition=models.Q(('to_address', ''), _negated=True), name='outbound_message_has_somewhere_to_go'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'sent'), _negated=True), ('sent_at__isnull', False), _connector='OR'), name='sent_message_records_when'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'failed'), _negated=True), ('failed_at__isnull', False), _connector='OR'), name='failed_message_records_when')],
            },
        ),
    ]
