# Generated by Django 6.1.1 on 2026-09-07 02:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        ('patients', '0004_patient_patient_phone_trgm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_number', models.CharField(editable=False, max_length=40, unique=True)),
                ('visit_type', models.CharField(choices=[('outpatient', 'Outpatient'), ('walk_in', 'Walk-in'), ('follow_up', 'Follow-up')], default='walk_in', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('waiting', 'Waiting'), ('called', 'Called'), ('in_consultation', 'In consultation'), ('sent_for_investigation', 'Sent for investigation'), ('sent_to_pharmacy', 'Sent to pharmacy'), ('sent_for_billing', 'Sent for billing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='waiting', max_length=25)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('consultation_started_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visits_checked_in', to=settings.AUTH_USER_MODEL)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='facilities.clinic')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='facilities.facility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='patients.patient')),
            ],
            options={
                'ordering': ['arrived_at'],
                'permissions': [('check_in_patient', 'Can check a patient in'), ('move_queue', 'Can move a patient through the queue')],
            },
        ),
        migrations.CreateModel(
            name='VisitStateChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=25)),
                ('to_status', models.CharField(max_length=25)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_changes', to='visits.visit')),
            ],
            options={
                'ordering': ['changed_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['facility', 'status', 'arrived_at'], name='visits_visi_facilit_46c103_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['patient', '-arrived_at'], name='visits_visi_patient_9531d2_idx'),
        ),
        migrations.AddConstraint(
            model_name='visit',
            constraint=models.UniqueConstraint(condition=models.Q(('closed_at__isnull', True)), fields=('patient',), name='one_open_visit_per_patient'),
        ),
    ]
