# Generated by Django 6.1.1 on 2026-09-07 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('waiting', 'Waiting'), ('called', 'Called'), ('in_consultation', 'In consultation'), ('sent_for_investigation', 'Sent for investigation'), ('sent_to_pharmacy', 'Sent to pharmacy'), ('sent_for_billing', 'Sent for billing'), ('admitted', 'Admitted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='waiting', max_length=25),
        ),
    ]
