# Generated by Django 6.1.1 on 2026-09-10 04:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
        ('visits', '0002_alter_visit_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TriageLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField(help_text='1 is the most urgent. The queue sorts by this.')),
                ('name', models.CharField(max_length=60)),
                ('colour', models.CharField(blank=True, help_text='What the department calls it on the wall: red, orange, green.', max_length=20)),
                ('target_minutes', models.PositiveSmallIntegerField(blank=True, help_text='How long this level should wait before being seen.', null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['scale', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_mode', models.CharField(choices=[('walk_in', 'Walked in'), ('ambulance', 'Ambulance'), ('police', 'Police'), ('referred', 'Referred by another clinician'), ('transfer', 'Transferred from another hospital')], default='walk_in', max_length=12)),
                ('presenting_complaint', models.CharField(max_length=255)),
                ('brought_in_by', models.CharField(blank=True, help_text='Ambulance service, relative, police unit — whoever handed over.', max_length=200)),
                ('circumstances', models.TextField(blank=True, help_text='What the crew could say: where they were found, what they were wearing. Often the only thing that lets a relative confirm an unidentified patient is theirs.')),
                ('outcome', models.CharField(blank=True, choices=[('admitted', 'Admitted'), ('transferred', 'Transferred to another hospital'), ('referred', 'Referred on'), ('discharged', 'Discharged'), ('died', 'Died'), ('lwbs', 'Left without being seen')], max_length=12)),
                ('outcome_at', models.DateTimeField(blank=True, null=True)),
                ('outcome_note', models.TextField(blank=True)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('outcome_recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emergency_outcomes', to=settings.AUTH_USER_MODEL)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='emergency_episode', to='visits.visit')),
            ],
            options={
                'ordering': ['-opened_at', '-id'],
                'permissions': [('triage_patient', 'Can triage a patient in the emergency department'), ('close_emergency_episode', 'Can record how an emergency episode ended')],
            },
        ),
        migrations.CreateModel(
            name='TriageAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField(help_text='1 for the triage on arrival; higher for each re-triage.')),
                ('complaint', models.CharField(blank=True, max_length=255)),
                ('observations', models.TextField(blank=True, help_text='What was measured or seen at this assessment.')),
                ('reason_for_retriage', models.CharField(blank=True, help_text='Required on a re-triage. Why the severity changed.', max_length=255)),
                ('assessed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assessed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='triage_assessments', to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triage_assessments', to='visits.emergencyepisode')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='visits.triagelevel')),
            ],
            options={
                'ordering': ['episode', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='TriageScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='triage_scales', to='facilities.facility')),
            ],
            options={
                'ordering': ['facility', 'name'],
            },
        ),
        migrations.AddField(
            model_name='triagelevel',
            name='scale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='visits.triagescale'),
        ),
        migrations.AddConstraint(
            model_name='emergencyepisode',
            constraint=models.CheckConstraint(condition=models.Q(('presenting_complaint', ''), _negated=True), name='emergency_episode_states_a_complaint'),
        ),
        migrations.AddConstraint(
            model_name='emergencyepisode',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('outcome', ''), ('outcome_at__isnull', True)), models.Q(models.Q(('outcome', ''), _negated=True), ('outcome_at__isnull', False)), _connector='OR'), name='emergency_outcome_carries_its_time'),
        ),
        migrations.AddConstraint(
            model_name='emergencyepisode',
            constraint=models.CheckConstraint(condition=models.Q(('outcome', ''), ('outcome_recorded_by__isnull', False), _connector='OR'), name='emergency_outcome_names_who_recorded_it'),
        ),
        migrations.AddConstraint(
            model_name='triageassessment',
            constraint=models.UniqueConstraint(fields=('episode', 'sequence'), name='one_assessment_per_sequence_per_episode'),
        ),
        migrations.AddConstraint(
            model_name='triageassessment',
            constraint=models.CheckConstraint(condition=models.Q(('sequence', 1), models.Q(('reason_for_retriage', ''), _negated=True), _connector='OR'), name='retriage_states_why'),
        ),
        migrations.AddConstraint(
            model_name='triagescale',
            constraint=models.UniqueConstraint(fields=('facility', 'name'), name='one_triage_scale_name_per_facility'),
        ),
        migrations.AddConstraint(
            model_name='triagescale',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('facility',), name='one_active_triage_scale_per_facility'),
        ),
        migrations.AddConstraint(
            model_name='triagelevel',
            constraint=models.UniqueConstraint(fields=('scale', 'rank'), name='one_level_per_rank_per_scale'),
        ),
        migrations.AddConstraint(
            model_name='triagelevel',
            constraint=models.CheckConstraint(condition=models.Q(('rank__gte', 1)), name='triage_rank_starts_at_one'),
        ),
    ]
