# Generated by Django 6.1.1 on 2026-09-07 02:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        ('patients', '0004_patient_patient_phone_trgm'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encounter_type', models.CharField(choices=[('consultation', 'Consultation'), ('review', 'Review'), ('triage', 'Triage')], default='consultation', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('final', 'Final'), ('amended', 'Amended')], default='draft', max_length=10)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finalised_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='facilities.facility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='patients.patient')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='visits.visit')),
            ],
            options={
                'ordering': ['-started_at'],
                'permissions': [('finalise_encounter', 'Can finalise a consultation record'), ('amend_encounter', 'Can amend a finalised consultation record')],
            },
        ),
        migrations.CreateModel(
            name='EncounterVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('is_current', models.BooleanField(default=True)),
                ('presenting_complaint', models.TextField(blank=True)),
                ('history_of_presenting_complaint', models.TextField(blank=True)),
                ('past_medical_history', models.TextField(blank=True)),
                ('surgical_history', models.TextField(blank=True)),
                ('family_history', models.TextField(blank=True)),
                ('social_history', models.TextField(blank=True)),
                ('medication_history', models.TextField(blank=True)),
                ('examination_findings', models.TextField(blank=True)),
                ('clinical_notes', models.TextField(blank=True)),
                ('treatment_plan', models.TextField(blank=True)),
                ('follow_up_plan', models.TextField(blank=True)),
                ('authored_at', models.DateTimeField(auto_now_add=True)),
                ('amendment_reason', models.TextField(blank=True)),
                ('amends', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='amended_by', to='clinical.encounterversion')),
                ('authored_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encounter_versions', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='clinical.encounter')),
            ],
            options={
                'ordering': ['encounter', 'version_number'],
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_system', models.CharField(blank=True, help_text='e.g. ICD-10, LOINC, ATC', max_length=64)),
                ('code', models.CharField(blank=True, max_length=64)),
                ('code_display', models.CharField(blank=True, max_length=255)),
                ('code_version', models.CharField(blank=True, help_text='Release of the code system used.', max_length=32)),
                ('description', models.CharField(max_length=255)),
                ('certainty', models.CharField(choices=[('confirmed', 'Confirmed'), ('provisional', 'Provisional'), ('differential', 'Differential')], default='provisional', max_length=15)),
                ('is_primary', models.BooleanField(default=False)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='clinical.encounterversion')),
            ],
            options={
                'verbose_name_plural': 'diagnoses',
                'ordering': ['-is_primary', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(25), django.core.validators.MaxValueValidator(45)])),
                ('systolic_bp', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(300)])),
                ('diastolic_bp', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(200)])),
                ('pulse_bpm', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(250)])),
                ('respiratory_rate', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(80)])),
                ('oxygen_saturation', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(100)])),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.3), django.core.validators.MaxValueValidator(400)])),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(260)])),
                ('blood_glucose_mmol', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(50)])),
                ('pain_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10)])),
                ('is_erroneous', models.BooleanField(default=False, help_text='Marked as recorded in error. The reading is kept.')),
                ('error_reason', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vital_signs', to='facilities.facility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vital_signs', to='patients.patient')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vitals_recorded', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vital_signs', to='visits.visit')),
            ],
            options={
                'verbose_name': 'vital signs',
                'verbose_name_plural': 'vital signs',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['patient', '-started_at'], name='clinical_en_patient_3225be_idx'),
        ),
        migrations.AddConstraint(
            model_name='encounterversion',
            constraint=models.UniqueConstraint(fields=('encounter', 'version_number'), name='encounter_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='encounterversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('encounter',), name='one_current_version_per_encounter'),
        ),
        migrations.AddConstraint(
            model_name='encounterversion',
            constraint=models.CheckConstraint(condition=models.Q(('version_number', 1), models.Q(('amendment_reason', ''), _negated=True), _connector='OR'), name='amendment_states_a_reason'),
        ),
        migrations.AddIndex(
            model_name='vitalsigns',
            index=models.Index(fields=['patient', '-recorded_at'], name='clinical_vi_patient_4ccd3e_idx'),
        ),
        migrations.AddConstraint(
            model_name='vitalsigns',
            constraint=models.CheckConstraint(condition=models.Q(('systolic_bp__isnull', True), ('diastolic_bp__isnull', True), ('systolic_bp__gt', models.F('diastolic_bp')), _connector='OR'), name='systolic_above_diastolic'),
        ),
        migrations.AddConstraint(
            model_name='vitalsigns',
            constraint=models.CheckConstraint(condition=models.Q(('is_erroneous', False), models.Q(('error_reason', ''), _negated=True), _connector='OR'), name='erroneous_vitals_state_a_reason'),
        ),
    ]
