# Generated by Django 6.1.1 on 2026-09-07 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_alter_vitalsigns_weight_kg'),
        ('facilities', '0001_initial'),
        ('inpatient', '0001_initial'),
        ('patients', '0004_patient_patient_phone_trgm'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='inpatient.admission'),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vital_signs', to='inpatient.admission'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='encounter_type',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('review', 'Review'), ('triage', 'Triage'), ('daily_review', 'Inpatient daily review')], default='consultation', max_length=20),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='visits.visit'),
        ),
        migrations.AddConstraint(
            model_name='encounter',
            constraint=models.CheckConstraint(condition=models.Q(('visit__isnull', False), ('admission__isnull', False), _connector='OR'), name='encounter_belongs_to_a_visit_or_an_admission'),
        ),
    ]
