# Generated by Django 6.1.1 on 2026-09-10 04:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0003_encounter_admission_vitalsigns_admission_and_more'),
        ('facilities', '0001_initial'),
        ('inpatient', '0003_scheduleddose_outstanding_doses_by_admission'),
        ('patients', '0004_patient_patient_phone_trgm'),
        ('visits', '0002_alter_visit_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=30, unique=True)),
                ('kind', models.CharField(choices=[('internal', 'Within this hospital group'), ('external', 'To another organisation')], max_length=10)),
                ('to_organisation', models.CharField(blank=True, max_length=200)),
                ('to_external_clinician', models.CharField(blank=True, max_length=200)),
                ('to_address', models.TextField(blank=True)),
                ('reason', models.TextField(help_text='Why this patient is being referred.')),
                ('clinical_question', models.TextField(help_text='What is being asked of the person receiving it. A referral without a question is a transfer of responsibility, not a request for an opinion.')),
                ('what_was_sent', models.TextField(blank=True, help_text='Results, images and letters that went with it.')),
                ('urgency', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('two_week', 'Urgent, suspected cancer')], default='routine', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('seen', 'Patient seen'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='draft', max_length=10)),
                ('referred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.TextField(blank=True, help_text='What the receiving clinician found or advised.')),
                ('outcome_recorded_at', models.DateTimeField(blank=True, null=True)),
                ('print_count', models.PositiveSmallIntegerField(default=0)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='inpatient.admission')),
                ('encounter', models.ForeignKey(blank=True, help_text='The consultation this came out of, where there was one.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='clinical.encounter')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='facilities.facility')),
                ('outcome_recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referral_outcomes_recorded', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='patients.patient')),
                ('referred_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
                ('to_clinician', models.ForeignKey(blank=True, help_text='Named clinician, where the referral is to a person rather than a department.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referrals_received', to=settings.AUTH_USER_MODEL)),
                ('to_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referrals_in', to='facilities.department')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='visits.visit')),
            ],
            options={
                'ordering': ['-referred_at', '-id'],
                'permissions': [('make_referral', 'Can refer a patient'), ('record_referral_outcome', 'Can record what a referral came back with')],
            },
        ),
        migrations.CreateModel(
            name='ReferralPrint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_reprint', models.BooleanField(default=False)),
                ('printed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referral_prints', to=settings.AUTH_USER_MODEL)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prints', to='clinical.referral')),
            ],
            options={
                'ordering': ['-printed_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='referral',
            constraint=models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='referral_states_a_reason'),
        ),
        migrations.AddConstraint(
            model_name='referral',
            constraint=models.CheckConstraint(condition=models.Q(('clinical_question', ''), _negated=True), name='referral_asks_a_question'),
        ),
        migrations.AddConstraint(
            model_name='referral',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'internal'), ('to_department__isnull', False)), models.Q(('kind', 'internal'), ('to_clinician__isnull', False)), models.Q(('kind', 'external'), models.Q(('to_organisation', ''), _negated=True)), _connector='OR'), name='referral_has_a_destination'),
        ),
        migrations.AddConstraint(
            model_name='referral',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['seen', 'declined']), _negated=True), ('outcome_recorded_at__isnull', False), _connector='OR'), name='closed_referral_records_its_outcome'),
        ),
    ]
