# Generated by Django 6.1.1 on 2026-09-07 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
        ('billing', '0001_initial'),
        ('facilities', '0001_initial'),
        ('patients', '0004_patient_patient_phone_trgm'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invoice',
            name='one_draft_invoice_per_visit',
        ),
        migrations.AddField(
            model_name='invoice',
            name='admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='admissions.admission'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('admission__isnull', True), ('status', 'draft')), fields=('visit',), name='one_draft_invoice_per_visit'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'draft')), fields=('admission',), name='one_draft_invoice_per_admission'),
        ),
    ]
