# Generated by Django 6.1.1 on 2026-09-07 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invoice',
            name='one_draft_invoice_per_visit',
        ),
    ]
