# Generated by Django 6.1.1 on 2026-09-09 08:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_invoice_admission_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('shortage', 'Shortage found after reconciliation'), ('overage', 'Overage found after reconciliation'), ('misposted', 'Taken against the wrong method or session')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField()),
                ('raised_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='session_adjustments', to='billing.paymentmethod')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_adjustments', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='billing.cashiersession')),
            ],
            options={
                'ordering': ['-raised_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount', 0), _negated=True), name='adjustment_is_not_zero'), models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='adjustment_states_a_reason')],
            },
        ),
        migrations.CreateModel(
            name='SessionCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counted', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.CharField(blank=True, help_text='Required where the count disagrees with what was taken.', max_length=255)),
                ('counted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_counts', to='billing.paymentmethod')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counts', to='billing.cashiersession')),
            ],
            options={
                'ordering': ['session', 'method__name'],
                'constraints': [models.UniqueConstraint(fields=('session', 'method'), name='one_count_per_session_and_method'), models.CheckConstraint(condition=models.Q(('counted__gte', 0)), name='count_not_negative')],
            },
        ),
        migrations.CreateModel(
            name='TillHandover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('float_handed', models.DecimalField(decimal_places=2, max_digits=12)),
                ('handed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('from_session', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='handed_over', to='billing.cashiersession')),
                ('handed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tills_handed_over', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tills_received', to=settings.AUTH_USER_MODEL)),
                ('to_session', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='received_from', to='billing.cashiersession')),
            ],
            options={
                'ordering': ['-handed_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('float_handed__gte', 0)), name='handover_float_not_negative'), models.CheckConstraint(condition=models.Q(('handed_by', models.F('received_by')), _negated=True), name='handover_needs_two_people')],
            },
        ),
    ]
