# Generated by Django 6.1.1 on 2026-09-09 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_sessionadjustment_sessioncount_tillhandover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashiersession',
            options={'ordering': ['-opened_at'], 'permissions': [('reconcile_cashiersession', 'Can reconcile a cashier session'), ('adjust_cashiersession', 'Can adjust a reconciled cashier session'), ('receive_till', 'Can receive a till handed over by another cashier')]},
        ),
    ]
