# Generated by Django 6.1.1 on 2026-09-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalApiAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'external API access',
                'permissions': [('use_external_api', 'Can read through the external API facade')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
