# Generated by Django 6.1.1 on 2026-09-07 22:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0003_invoice_admission_and_more'),
        ('facilities', '0001_initial'),
        ('inpatient', '0003_scheduleddose_outstanding_doses_by_admission'),
        ('patients', '0004_patient_patient_phone_trgm'),
        ('visits', '0002_alter_visit_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagingModality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('code', models.CharField(help_text='DICOM-style, e.g. CR, US, CT', max_length=12, unique=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'imaging modalities',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ImagingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=40, unique=True)),
                ('ordered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent')], default='routine', max_length=10)),
                ('clinical_question', models.TextField(help_text='What the requesting clinician needs answered. The radiologist reads this.')),
                ('relevant_history', models.TextField(blank=True)),
                ('is_pregnant', models.BooleanField(default=False, help_text='Declared at ordering; the department needs it before ionising radiation.')),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='imaging_orders', to='inpatient.admission')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imaging_orders', to='facilities.facility')),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imaging_orders', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imaging_orders', to='patients.patient')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='imaging_orders', to='visits.visit')),
            ],
            options={
                'ordering': ['-ordered_at'],
            },
        ),
        migrations.CreateModel(
            name='ImagingProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_system', models.CharField(blank=True, help_text='e.g. ICD-10, LOINC, ATC', max_length=64)),
                ('code', models.CharField(blank=True, max_length=64)),
                ('code_display', models.CharField(blank=True, max_length=255)),
                ('code_version', models.CharField(blank=True, help_text='Release of the code system used.', max_length=32)),
                ('name', models.CharField(max_length=200)),
                ('code_short', models.CharField(help_text='What the department calls it, e.g. CXR', max_length=20, unique=True)),
                ('body_part', models.CharField(max_length=100)),
                ('preparation_instructions', models.TextField(blank=True, help_text='Shown to the ward and to the patient when the order is placed.')),
                ('typical_minutes', models.PositiveSmallIntegerField(default=15, help_text='Used for scheduling, not for billing.')),
                ('requires_contrast', models.BooleanField(default=False)),
                ('contraindications', models.CharField(blank=True, help_text='Shown at ordering. Pregnancy, pacemaker, renal impairment.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('modality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedures', to='imaging.imagingmodality')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='imaging_procedures', to='billing.service')),
            ],
            options={
                'ordering': ['modality__display_order', 'name'],
                'permissions': [('verify_imagingreport', 'Can verify and release an imaging report'), ('amend_imagingreport', 'Can amend a verified imaging report'), ('acknowledge_critical_finding', 'Can acknowledge a critical imaging finding'), ('perform_imaging', 'Can record an examination as performed'), ('schedule_imaging', 'Can schedule an imaging examination')],
            },
        ),
        migrations.CreateModel(
            name='ImagingOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('scheduled', 'Scheduled'), ('performed', 'Performed, awaiting a report'), ('reported', 'Reported, awaiting verification'), ('verified', 'Verified'), ('cancelled', 'Cancelled')], default='requested', max_length=12)),
                ('cancelled_reason', models.CharField(blank=True, max_length=255)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('performed_at', models.DateTimeField(blank=True, null=True)),
                ('accession_number', models.CharField(blank=True, help_text="The department's own study identifier.", max_length=60)),
                ('views_taken', models.CharField(blank=True, max_length=255)),
                ('technique_note', models.CharField(blank=True, max_length=255)),
                ('contrast_given', models.CharField(blank=True, max_length=120)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='imaging.imagingorder')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='imaging_performed', to=settings.AUTH_USER_MODEL)),
                ('scheduled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='imaging_scheduled', to=settings.AUTH_USER_MODEL)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='imaging.imagingprocedure')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ImagingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('findings', models.TextField()),
                ('conclusion', models.TextField()),
                ('comparison', models.CharField(blank=True, help_text='Previous studies compared against.', max_length=255)),
                ('is_critical', models.BooleanField(default=False)),
                ('critical_finding', models.CharField(blank=True, help_text='What has to be acted on, in one line.', max_length=255)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current', models.BooleanField(default=True)),
                ('amendment_reason', models.TextField(blank=True)),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('amends', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='amended_by', to='imaging.imagingreport')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='imaging.imagingorderitem')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imaging_reports', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='imaging_reports_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order_item', 'version'],
            },
        ),
        migrations.CreateModel(
            name='CriticalFindingAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acknowledged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('action_taken', models.TextField()),
                ('acknowledged_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='critical_findings_acknowledged', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acknowledgements', to='imaging.imagingreport')),
            ],
            options={
                'ordering': ['-acknowledged_at'],
            },
        ),
        migrations.AddIndex(
            model_name='imagingorder',
            index=models.Index(fields=['patient', '-ordered_at'], name='imaging_ima_patient_7ba678_idx'),
        ),
        migrations.AddConstraint(
            model_name='imagingorder',
            constraint=models.CheckConstraint(condition=models.Q(('visit__isnull', False), ('admission__isnull', False), _connector='OR'), name='imaging_order_belongs_to_a_visit_or_an_admission'),
        ),
        migrations.AddConstraint(
            model_name='imagingorder',
            constraint=models.CheckConstraint(condition=models.Q(('clinical_question', ''), _negated=True), name='imaging_order_states_a_clinical_question'),
        ),
        migrations.AddConstraint(
            model_name='imagingorderitem',
            constraint=models.UniqueConstraint(fields=('order', 'procedure'), name='procedure_once_per_imaging_order'),
        ),
        migrations.AddConstraint(
            model_name='imagingorderitem',
            constraint=models.UniqueConstraint(condition=models.Q(('accession_number', ''), _negated=True), fields=('accession_number',), name='accession_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='imagingorderitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'cancelled'), _negated=True), models.Q(('cancelled_reason', ''), _negated=True), _connector='OR'), name='cancelled_imaging_states_a_reason'),
        ),
        migrations.AddConstraint(
            model_name='imagingorderitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['performed', 'reported', 'verified']), _negated=True), ('performed_at__isnull', False), _connector='OR'), name='performed_imaging_records_when'),
        ),
        migrations.AddConstraint(
            model_name='imagingreport',
            constraint=models.UniqueConstraint(fields=('order_item', 'version'), name='imaging_report_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='imagingreport',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('order_item',), name='one_current_imaging_report'),
        ),
        migrations.AddConstraint(
            model_name='imagingreport',
            constraint=models.CheckConstraint(condition=models.Q(('version', 1), models.Q(('amendment_reason', ''), _negated=True), _connector='OR'), name='imaging_amendment_states_a_reason'),
        ),
        migrations.AddConstraint(
            model_name='imagingreport',
            constraint=models.CheckConstraint(condition=models.Q(('is_critical', False), models.Q(('critical_finding', ''), _negated=True), _connector='OR'), name='critical_finding_says_what'),
        ),
        migrations.AddConstraint(
            model_name='imagingreport',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('findings', ''), _negated=True), models.Q(('conclusion', ''), _negated=True)), name='imaging_report_has_findings_and_a_conclusion'),
        ),
        migrations.AddConstraint(
            model_name='criticalfindingacknowledgement',
            constraint=models.CheckConstraint(condition=models.Q(('action_taken', ''), _negated=True), name='critical_finding_acknowledgement_says_what_was_done'),
        ),
    ]
