# Generated by Django 6.1.1 on 2026-09-07 13:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        ('patients', '0004_patient_patient_phone_trgm'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BedTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('moved_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-moved_at'],
            },
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(editable=False, max_length=40, unique=True)),
                ('admission_reason', models.TextField()),
                ('admission_diagnosis', models.CharField(max_length=255)),
                ('admitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('admitted', 'Admitted'), ('discharge_planned', 'Discharge planned'), ('discharged', 'Discharged')], default='admitted', max_length=20)),
                ('expected_discharge_date', models.DateField(blank=True, null=True)),
                ('discharge_destination', models.CharField(blank=True, choices=[('home', 'Home'), ('transferred', 'Transferred to another facility'), ('absconded', 'Absconded'), ('died', 'Died')], max_length=15)),
                ('discharge_plan_notes', models.TextField(blank=True)),
                ('discharged_at', models.DateTimeField(blank=True, null=True)),
                ('discharge_diagnosis', models.CharField(blank=True, max_length=255)),
                ('follow_up_instructions', models.TextField(blank=True)),
                ('billing_override_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions_made', to=settings.AUTH_USER_MODEL)),
                ('discharged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discharges_completed', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='facilities.facility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='patients.patient')),
                ('responsible_consultant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patients_under_care', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='visits.visit')),
            ],
            options={
                'ordering': ['-admitted_at'],
                'permissions': [('admit_patient', 'Can admit a patient and allocate a bed'), ('transfer_patient', 'Can move an inpatient between beds or wards'), ('plan_discharge', 'Can record a discharge plan'), ('discharge_patient', 'Can complete a discharge'), ('override_discharge_billing', 'Can discharge despite an unpaid balance')],
            },
        ),
        migrations.CreateModel(
            name='AdmissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('working_diagnosis', models.CharField(max_length=255)),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent')], default='routine', max_length=10)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Awaiting a bed'), ('admitted', 'Admitted'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.CharField(blank=True, max_length=255)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admission_requests_decided', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admission_requests', to='facilities.facility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admission_requests', to='patients.patient')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admission_requests_made', to=settings.AUTH_USER_MODEL)),
                ('responsible_consultant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admission_requests_under_care', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(blank=True, help_text='The attendance the request came out of, where there was one.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admission_requests', to='visits.visit')),
            ],
            options={
                'ordering': ['-priority', 'requested_at'],
                'permissions': [('decide_admissionrequest', 'Can accept or decline an admission request')],
            },
        ),
    ]
