# Generated by Django 6.1.1 on 2026-09-07 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0001_initial'),
        ('wards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionrequest',
            name='ward',
            field=models.ForeignKey(help_text='Where the requesting clinician believes the patient should go.', on_delete=django.db.models.deletion.PROTECT, related_name='admission_requests', to='wards.ward'),
        ),
        migrations.AddField(
            model_name='admission',
            name='request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admission', to='admissions.admissionrequest'),
        ),
        migrations.AddField(
            model_name='bedtransfer',
            name='admission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='admissions.admission'),
        ),
        migrations.AddField(
            model_name='bedtransfer',
            name='authorised_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_authorised', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bedtransfer',
            name='from_occupancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='wards.bedoccupancy'),
        ),
        migrations.AddField(
            model_name='bedtransfer',
            name='to_occupancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='wards.bedoccupancy'),
        ),
        migrations.AddIndex(
            model_name='admissionrequest',
            index=models.Index(fields=['ward', 'status', 'requested_at'], name='admissions__ward_id_8f4b59_idx'),
        ),
        migrations.AddConstraint(
            model_name='admissionrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'declined'), _negated=True), models.Q(('decline_reason', ''), _negated=True), _connector='OR'), name='declined_request_states_a_reason'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['facility', 'status', '-admitted_at'], name='admissions__facilit_bbe8d8_idx'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['patient', '-admitted_at'], name='admissions__patient_8fea24_idx'),
        ),
        migrations.AddConstraint(
            model_name='admission',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'discharged'), _negated=True), fields=('patient',), name='one_open_admission_per_patient'),
        ),
        migrations.AddConstraint(
            model_name='admission',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'discharged'), _negated=True), models.Q(('discharged_at__isnull', False), models.Q(('discharge_diagnosis', ''), _negated=True)), _connector='OR'), name='discharged_admission_is_complete'),
        ),
    ]
