# Generated by Django 6.1.1 on 2026-09-07 13:26

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0001_initial'),
        ('billing', '0002_remove_invoice_one_draft_invoice_per_visit_and_more'),
        ('facilities', '0001_initial'),
        ('patients', '0004_patient_patient_phone_trgm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['ward', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('service_state', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('cleaning', 'Being cleaned'), ('maintenance', 'Unavailable for maintenance')], default='available', max_length=15)),
                ('state_note', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beds', to='wards.room')),
            ],
            options={
                'ordering': ['room', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=20)),
                ('ward_type', models.CharField(choices=[('general', 'General'), ('male', 'Male'), ('female', 'Female'), ('paediatric', 'Paediatric'), ('maternity', 'Maternity'), ('intensive', 'Intensive care'), ('isolation', 'Isolation')], default='general', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wards', to='facilities.department')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wards', to='facilities.facility')),
                ('nightly_service', models.ForeignKey(blank=True, help_text='Service used to charge each bed night.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wards', to='billing.service')),
            ],
            options={
                'ordering': ['facility', 'name'],
                'permissions': [('manage_beds', 'Can change bed availability and take beds out of service')],
            },
        ),
        migrations.AddField(
            model_name='room',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='wards.ward'),
        ),
        migrations.CreateModel(
            name='EscalationThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement', models.CharField(choices=[('temperature_c', 'Temperature (°C)'), ('systolic_bp', 'Systolic BP (mmHg)'), ('diastolic_bp', 'Diastolic BP (mmHg)'), ('pulse_bpm', 'Pulse (bpm)'), ('respiratory_rate', 'Respiratory rate'), ('oxygen_saturation', 'Oxygen saturation (%)'), ('blood_glucose_mmol', 'Blood glucose (mmol/L)')], max_length=30)),
                ('low', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('high', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('instruction', models.CharField(blank=True, help_text='What the nurse should do. Shown with the alert.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_thresholds', to='wards.ward')),
            ],
            options={
                'ordering': ['ward', 'measurement'],
            },
        ),
        migrations.CreateModel(
            name='BedOccupancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ('reason_ended', models.CharField(blank=True, max_length=120)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occupancies', to='admissions.admission')),
                ('allocated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bed_allocations', to=settings.AUTH_USER_MODEL)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occupancies', to='wards.bed')),
                ('ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bed_releases', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bed_occupancies', to='patients.patient')),
            ],
            options={
                'verbose_name_plural': 'bed occupancies',
                'ordering': ['bed', 'period'],
                'indexes': [models.Index(fields=['admission'], name='wards_bedoc_admissi_74671d_idx')],
                'constraints': [django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('period', '&&'), ('bed', '=')], name='one_patient_per_bed_at_a_time'), django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('period', '&&'), ('patient', '=')], name='one_bed_per_patient_at_a_time')],
            },
        ),
        migrations.AddConstraint(
            model_name='bed',
            constraint=models.UniqueConstraint(fields=('room', 'code'), name='bed_code_unique_per_room'),
        ),
        migrations.AddConstraint(
            model_name='ward',
            constraint=models.UniqueConstraint(fields=('facility', 'code'), name='ward_code_unique_per_facility'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('ward', 'code'), name='room_code_unique_per_ward'),
        ),
        migrations.AddConstraint(
            model_name='escalationthreshold',
            constraint=models.UniqueConstraint(fields=('ward', 'measurement'), name='one_threshold_per_ward_measurement'),
        ),
        migrations.AddConstraint(
            model_name='escalationthreshold',
            constraint=models.CheckConstraint(condition=models.Q(('low__isnull', False), ('high__isnull', False), _connector='OR'), name='threshold_bounds_at_least_one'),
        ),
    ]
