# Generated by Django 6.1.1 on 2026-09-09 08:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        ('inpatient', '0003_scheduleddose_outstanding_doses_by_admission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'item categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StockLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(max_length=60)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('quantity_on_hand', models.IntegerField(default=0)),
                ('unit_cost', models.DecimalField(decimal_places=2, default='0.00', max_digits=12)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': [models.OrderBy(models.F('expiry_date'), nulls_last=True), 'received_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('unit_of_issue', models.CharField(help_text='What one of these is when it leaves the store: box, pair, litre.', max_length=40)),
                ('default_reorder_level', models.IntegerField(default=0)),
                ('is_controlled', models.BooleanField(default=False)),
                ('tracks_expiry', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.itemcategory')),
            ],
            options={
                'ordering': ['category__display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('count', 'Count correction'), ('damage', 'Damaged'), ('loss', 'Lost or unaccounted'), ('expiry', 'Written off, expired'), ('return_to_supplier', 'Returned to supplier')], max_length=20)),
                ('quantity_delta', models.IntegerField(help_text='Negative to write stock off, positive to add it back.')),
                ('value', models.DecimalField(decimal_places=2, default='0.00', max_digits=12)),
                ('reason', models.TextField()),
                ('raised_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('authorised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_adjustments_authorised', to=settings.AUTH_USER_MODEL)),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_adjustments_raised', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='inventory.stocklot')),
            ],
            options={
                'ordering': ['-raised_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reorder_level', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='inventory.inventoryitem')),
            ],
            options={
                'ordering': ['store', 'item__name'],
            },
        ),
        migrations.AddField(
            model_name='stocklot',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='inventory.stockrecord'),
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('moved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='inventory.inventoryitem')),
                ('moved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-moved_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('receipt', 'Goods received'), ('issue', 'Issued'), ('transfer_out', 'Transferred out'), ('transfer_in', 'Transferred in'), ('adjustment', 'Adjustment'), ('return', 'Returned to store')], max_length=20)),
                ('quantity_delta', models.IntegerField(help_text='Negative for stock leaving.')),
                ('quantity_after', models.IntegerField()),
                ('issued_to', models.CharField(blank=True, help_text='Ward, department or named recipient. Required for a controlled item.', max_length=160)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('adjustment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.stockadjustment')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.stocklot')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to=settings.AUTH_USER_MODEL)),
                ('transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.stocktransfer')),
            ],
            options={
                'ordering': ['-recorded_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=20)),
                ('kind', models.CharField(choices=[('main', 'Main store'), ('pharmacy', 'Pharmacy store'), ('ward', 'Ward store'), ('theatre', 'Theatre store'), ('laboratory', 'Laboratory store'), ('imaging', 'Imaging store')], default='main', max_length=15)),
                ('adjustment_authorisation_limit', models.DecimalField(decimal_places=2, default='0.00', help_text="Adjustments valued above this need a second person's authorisation. Zero means all of them do.", max_digits=12)),
                ('expiry_horizon_days', models.PositiveSmallIntegerField(default=90, help_text='Stock expiring within this many days is reported as expiring.')),
                ('is_active', models.BooleanField(default=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='facilities.facility')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores', to='inpatient.ward')),
            ],
            options={
                'ordering': ['facility', 'name'],
                'permissions': [('issue_stock', 'Can issue stock out of a store'), ('receive_stock', 'Can receive stock into a store'), ('transfer_stock', 'Can move stock between stores'), ('adjust_stock', 'Can adjust stock on hand'), ('authorise_stock_adjustment', "Can authorise another's adjustment")],
            },
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='from_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='inventory.store'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='to_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='inventory.store'),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='inventory.store'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('default_reorder_level__gte', 0)), name='item_reorder_level_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='stockadjustment',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_delta', 0), _negated=True), name='adjustment_changes_something'),
        ),
        migrations.AddConstraint(
            model_name='stockadjustment',
            constraint=models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='stock_adjustment_states_a_reason'),
        ),
        migrations.AddConstraint(
            model_name='stockadjustment',
            constraint=models.CheckConstraint(condition=models.Q(('authorised_by__isnull', True), models.Q(('authorised_by', models.F('raised_by')), _negated=True), _connector='OR'), name='adjustment_authorised_by_a_second_person'),
        ),
        migrations.AddIndex(
            model_name='stocklot',
            index=models.Index(fields=['record', 'expiry_date'], name='inventory_s_record__26bf36_idx'),
        ),
        migrations.AddConstraint(
            model_name='stocklot',
            constraint=models.UniqueConstraint(fields=('record', 'lot_number'), name='one_lot_per_record_and_number'),
        ),
        migrations.AddConstraint(
            model_name='stocklot',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_on_hand__gte', 0)), name='inventory_stock_never_negative'),
        ),
        migrations.AddConstraint(
            model_name='stocklot',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0)), name='lot_unit_cost_not_negative'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['lot', 'recorded_at'], name='inventory_s_lot_id_e225e5_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_delta', 0), _negated=True), name='movement_moves_something'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_after__gte', 0)), name='movement_balance_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='store',
            constraint=models.UniqueConstraint(fields=('facility', 'code'), name='store_code_unique_per_facility'),
        ),
        migrations.AddConstraint(
            model_name='store',
            constraint=models.CheckConstraint(condition=models.Q(('adjustment_authorisation_limit__gte', 0)), name='store_authorisation_limit_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='stocktransfer',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='transfer_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='stocktransfer',
            constraint=models.CheckConstraint(condition=models.Q(('from_store', models.F('to_store')), _negated=True), name='transfer_between_two_stores'),
        ),
        migrations.AddConstraint(
            model_name='stockrecord',
            constraint=models.UniqueConstraint(fields=('store', 'item'), name='one_record_per_store_and_item'),
        ),
        migrations.AddConstraint(
            model_name='stockrecord',
            constraint=models.CheckConstraint(condition=models.Q(('reorder_level__gte', 0)), name='record_reorder_level_not_negative'),
        ),
    ]
