# Generated by Django 6.1.1 on 2026-09-09 09:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('contact_name', models.CharField(blank=True, max_length=160)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('payment_terms_days', models.PositiveSmallIntegerField(default=30, help_text='Days from invoice to payment, as agreed.')),
                ('is_approved', models.BooleanField(default=True, help_text='Whether new orders may be placed. Past orders are unaffected.')),
                ('approval_note', models.CharField(blank=True, help_text='Why they are not approved, where they are not.', max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=30, unique=True)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('partially_received', 'Partially received'), ('received', 'Received in full'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('raised_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=255)),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='inventory.store')),
            ],
            options={
                'ordering': ['-raised_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=30, unique=True)),
                ('delivery_note', models.CharField(blank=True, max_length=60)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True)),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='inventory.purchaseorder')),
            ],
            options={
                'ordering': ['-received_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.IntegerField()),
                ('quantity_received', models.IntegerField(default=0)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='inventory.inventoryitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.purchaseorder')),
            ],
            options={
                'ordering': ['order', 'item__name'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('lot_number', models.CharField(max_length=60)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('movement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_line', to='inventory.stockmovement')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.goodsreceipt')),
                ('order_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_lines', to='inventory.purchaseorderline')),
            ],
            options={
                'ordering': ['receipt', 'order_line__item__name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=30, unique=True)),
                ('justification', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Awaiting approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('ordered', 'Ordered')], default='draft', max_length=12)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests_decided', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(help_text='Where the goods are to land.', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to='inventory.store')),
            ],
            options={
                'ordering': ['-requested_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='inventory.purchaserequest'),
        ),
        migrations.CreateModel(
            name='PurchaseRequestLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('estimated_unit_cost', models.DecimalField(decimal_places=2, default='0.00', max_digits=12)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_lines', to='inventory.inventoryitem')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.purchaserequest')),
            ],
            options={
                'ordering': ['request', 'item__name'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='inventory.supplier'),
        ),
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_reference', models.CharField(help_text="The number on the supplier's own invoice.", max_length=60)),
                ('invoice_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('received', 'Received'), ('matched', 'Matched'), ('queried', 'Queried'), ('approved', 'Approved for payment'), ('paid', 'Paid')], default='received', max_length=12)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('matched_value', models.DecimalField(blank=True, decimal_places=2, help_text='Value of what actually arrived, at ordered prices, when matched.', max_digits=14, null=True)),
                ('discrepancies', models.JSONField(blank=True, default=list, help_text='What did not match, in words, as at the time of matching.')),
                ('query_note', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoices_approved', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='inventory.purchaseorder')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-invoice_date', '-id'],
                'permissions': [('approve_purchase_request', 'Can approve a purchase request'), ('raise_purchase_order', 'Can raise a purchase order'), ('receive_goods', 'Can record goods received against an order'), ('approve_supplier_invoice', 'Can approve a supplier invoice for payment')],
            },
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.UniqueConstraint(fields=('order', 'item'), name='one_order_line_per_item'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_ordered__gt', 0)), name='order_line_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_received__gte', 0)), name='order_line_received_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_received__lte', models.F('quantity_ordered'))), name='order_line_not_over_received'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceiptline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='receipt_line_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='purchaserequest',
            constraint=models.CheckConstraint(condition=models.Q(('justification', ''), _negated=True), name='purchase_request_states_why'),
        ),
        migrations.AddConstraint(
            model_name='purchaserequest',
            constraint=models.CheckConstraint(condition=models.Q(('decided_by__isnull', True), models.Q(('decided_by', models.F('requested_by')), _negated=True), _connector='OR'), name='request_not_approved_by_its_own_requester'),
        ),
        migrations.AddConstraint(
            model_name='purchaserequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['approved', 'rejected', 'ordered']), _negated=True), ('decided_by__isnull', False), _connector='OR'), name='decided_request_names_who_decided'),
        ),
        migrations.AddConstraint(
            model_name='purchaserequestline',
            constraint=models.UniqueConstraint(fields=('request', 'item'), name='one_request_line_per_item'),
        ),
        migrations.AddConstraint(
            model_name='purchaserequestline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='request_line_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoice',
            constraint=models.UniqueConstraint(fields=('order', 'supplier_reference'), name='one_invoice_per_order_and_supplier_reference'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='supplier_invoice_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['approved', 'paid']), _negated=True), ('approved_by__isnull', False), _connector='OR'), name='approved_invoice_names_its_approver'),
        ),
    ]
