# Generated by Django 6.1.1 on 2026-09-09 09:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_supplier_purchaseorder_goodsreceipt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='purchaserequest',
            name='decided_request_names_who_decided',
        ),
        migrations.AddConstraint(
            model_name='purchaserequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['approved', 'rejected']), _negated=True), ('decided_by__isnull', False), _connector='OR'), name='decided_request_names_who_decided'),
        ),
    ]
