# Generated by Django 6.1.1 on 2026-09-08 12:47

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0003_invoice_admission_and_more'),
        ('facilities', '0001_initial'),
        ('inpatient', '0003_scheduleddose_outstanding_doses_by_admission'),
        ('patients', '0004_patient_patient_phone_trgm'),
        ('visits', '0002_alter_visit_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('provider_type', models.CharField(choices=[('hmo', 'HMO'), ('insurer', 'Private insurer'), ('government', 'Government scheme'), ('corporate', 'Corporate account')], default='hmo', max_length=12)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('claim_channel', models.CharField(choices=[('portal', 'Provider portal'), ('email', 'Email'), ('paper', 'Paper / hand delivered'), ('api', 'API')], default='portal', max_length=10)),
                ('claim_submission_note', models.CharField(blank=True, help_text='Where claims actually go. A portal URL, an address, a person.', max_length=255)),
                ('settlement_days', models.PositiveSmallIntegerField(default=30, help_text='Days they undertake to settle in.')),
                ('is_accepting_claims', models.BooleanField(default=True, help_text='Turn off a provider that has stopped paying. History stays readable.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'permissions': [('manage_coverage', 'Can configure providers, plans and coverage rules'), ('verify_eligibility', 'Can record an eligibility check'), ('request_preauthorisation', 'Can request and record a preauthorisation'), ('submit_claim', 'Can submit a claim to a provider'), ('record_claim_outcome', 'Can record an acknowledgement, rejection or payment'), ('write_off_claim_shortfall', 'Can write off an unpaid claim balance')],
            },
        ),
        migrations.CreateModel(
            name='ChargeCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('patient_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('basis', models.CharField(choices=[('full', 'Scheme pays in full'), ('percentage', 'Scheme pays a percentage'), ('fixed_copay', 'Patient pays a fixed co-pay, scheme pays the rest'), ('excluded', 'Not covered — the patient pays')], max_length=12)),
                ('applied_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('applied_copay', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rule_description', models.CharField(help_text='How this split was arrived at, in words, for the patient.', max_length=255)),
                ('hold_reason', models.CharField(blank=True, choices=[('no_preauthorisation', 'Awaiting preauthorisation'), ('expired_preauthorisation', 'Preauthorisation expired'), ('no_rule', 'No coverage rule for this service'), ('limit_reached', 'Scheme limit reached')], max_length=30)),
                ('resolved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('service_date', models.DateField(help_text='The date the rules were judged against. Not the invoice date.')),
                ('invoice_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coverage', to='billing.invoiceitem')),
            ],
            options={
                'verbose_name_plural': 'charge coverages',
                'ordering': ['invoice_item'],
            },
        ),
        migrations.CreateModel(
            name='ClaimBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_number', models.CharField(editable=False, max_length=40, unique=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('acknowledged', 'Acknowledged by the provider'), ('part_paid', 'Part paid'), ('paid', 'Settled'), ('rejected', 'Rejected')], default='draft', max_length=14)),
                ('resubmission_reason', models.CharField(blank=True, max_length=255)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('provider_reference', models.CharField(blank=True, max_length=120)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims_created', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='facilities.facility')),
                ('resubmits', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resubmitted_as', to='insurance.claimbatch')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claims_submitted', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='insurance.insuranceprovider')),
            ],
            options={
                'verbose_name_plural': 'claim batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClaimLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('policy_number', models.CharField(max_length=60)),
                ('service_description', models.CharField(max_length=255)),
                ('service_code', models.CharField(blank=True, max_length=30)),
                ('service_date', models.DateField()),
                ('diagnosis_codes', models.CharField(blank=True, max_length=255)),
                ('clinician', models.CharField(blank=True, max_length=200)),
                ('authorisation_reference', models.CharField(blank=True, max_length=120)),
                ('claimed_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('written_off_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('moved_to_patient_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Awaiting the provider'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('shortfall_reason', models.CharField(blank=True, help_text='Why the scheme paid less than claimed. Required to write off.', max_length=255)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='insurance.claimbatch')),
                ('coverage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claim_lines', to='insurance.chargecoverage')),
            ],
            options={
                'ordering': ['claim', 'service_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CoverageRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basis', models.CharField(choices=[('full', 'Scheme pays in full'), ('percentage', 'Scheme pays a percentage'), ('fixed_copay', 'Patient pays a fixed co-pay, scheme pays the rest'), ('excluded', 'Not covered — the patient pays')], default='full', max_length=12)),
                ('scheme_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('patient_copay', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('requires_preauthorisation', models.BooleanField(default=False)),
                ('exclusion_reason', models.CharField(blank=True, help_text='Shown on the invoice line. An unexplained amount is a dispute.', max_length=255)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coverage_rules', to='billing.servicecategory')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coverage_rules', to='billing.service')),
            ],
            options={
                'ordering': ['plan', 'category__display_order', 'service__name'],
            },
        ),
        migrations.AddField(
            model_name='chargecoverage',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_to', to='insurance.coveragerule'),
        ),
        migrations.CreateModel(
            name='PatientPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(max_length=60)),
                ('member_name', models.CharField(blank=True, help_text='The principal member, where the patient is a dependant.', max_length=200)),
                ('is_dependant', models.BooleanField(default=False)),
                ('relationship', models.CharField(blank=True, max_length=60)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField(blank=True, help_text='Blank for an open-ended policy.', null=True)),
                ('precedence', models.PositiveSmallIntegerField(default=1, help_text='1 pays first. Only matters where a patient holds two.')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='patients.patient')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'patient policies',
                'ordering': ['patient', 'precedence'],
            },
        ),
        migrations.CreateModel(
            name='EligibilityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('confirmed', 'Confirmed eligible'), ('declined', 'Declined by the provider'), ('unreachable', 'Provider could not be reached')], max_length=12)),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('checked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eligibility_checks', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_checks', to='insurance.patientpolicy')),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
        migrations.AddField(
            model_name='chargecoverage',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='charge_coverages', to='insurance.patientpolicy'),
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=30)),
                ('unruled_services', models.CharField(choices=[('covered', "Covered at the plan's default rate"), ('excluded', 'Not covered — the patient pays')], default='excluded', help_text='What this plan does with a service no rule mentions.', max_length=10)),
                ('default_scheme_percent', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Percentage the scheme pays where a rule does not say otherwise.', max_digits=5)),
                ('annual_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Total the scheme will pay per patient per year. Blank for none.', max_digits=12, null=True)),
                ('per_visit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('requires_preauthorisation_above', models.DecimalField(blank=True, decimal_places=2, help_text='Any single charge above this needs an authorisation reference.', max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='insurance.insuranceprovider')),
            ],
            options={
                'ordering': ['provider__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='patientpolicy',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='insurance.plan'),
        ),
        migrations.AddField(
            model_name='coveragerule',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='insurance.plan'),
        ),
        migrations.CreateModel(
            name='Preauthorisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_for', models.TextField(help_text='What is being asked for, in words.')),
                ('estimated_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('declined', 'Declined'), ('expired', 'Expired')], default='requested', max_length=10)),
                ('reference', models.CharField(blank=True, help_text="The provider's authorisation code. A claim needs this.", max_length=120)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('decline_reason', models.CharField(blank=True, max_length=255)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preauthorisations', to='inpatient.admission')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preauthorisations', to='patients.patient')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preauthorisations', to='insurance.patientpolicy')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preauthorisations_requested', to=settings.AUTH_USER_MODEL)),
                ('services', models.ManyToManyField(blank=True, help_text='The services this authorisation covers.', related_name='preauthorisations', to='billing.service')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preauthorisations', to='visits.visit')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddField(
            model_name='chargecoverage',
            name='preauthorisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charge_coverages', to='insurance.preauthorisation'),
        ),
        migrations.CreateModel(
            name='ProviderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('received_on', models.DateField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_payments', to='facilities.facility')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_payments', to='billing.paymentmethod')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='insurance.insuranceprovider')),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provider_payments_reconciled', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_payments_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='insurance.claimline')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='insurance.providerpayment')),
            ],
            options={
                'ordering': ['payment', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='claimline',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'rejected'), _negated=True), fields=('coverage',), name='one_live_claim_line_per_charge'),
        ),
        migrations.AddConstraint(
            model_name='claimline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'rejected'), _negated=True), models.Q(('rejection_reason', ''), _negated=True), _connector='OR'), name='rejected_line_states_why'),
        ),
        migrations.AddConstraint(
            model_name='claimline',
            constraint=models.CheckConstraint(condition=models.Q(('written_off_amount', 0), models.Q(('shortfall_reason', ''), _negated=True), _connector='OR'), name='write_off_states_why'),
        ),
        migrations.AddConstraint(
            model_name='claimline',
            constraint=models.CheckConstraint(condition=models.Q(('paid_amount__gte', 0), ('written_off_amount__gte', 0), ('moved_to_patient_amount__gte', 0)), name='claim_line_amounts_not_negative'),
        ),
        migrations.AddIndex(
            model_name='claimbatch',
            index=models.Index(fields=['provider', 'status', '-created_at'], name='insurance_c_provide_16259d_idx'),
        ),
        migrations.AddConstraint(
            model_name='claimbatch',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='claim_period_ends_after_it_starts'),
        ),
        migrations.AddConstraint(
            model_name='claimbatch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'rejected'), _negated=True), models.Q(('rejection_reason', ''), _negated=True), _connector='OR'), name='rejected_claim_states_why'),
        ),
        migrations.AddConstraint(
            model_name='claimbatch',
            constraint=models.CheckConstraint(condition=models.Q(('resubmits__isnull', True), models.Q(('resubmission_reason', ''), _negated=True), _connector='OR'), name='resubmission_states_why'),
        ),
        migrations.AddConstraint(
            model_name='claimbatch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['submitted', 'acknowledged', 'part_paid', 'paid']), _negated=True), ('submitted_at__isnull', False), _connector='OR'), name='submitted_claim_records_when'),
        ),
        migrations.AddConstraint(
            model_name='eligibilitycheck',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('outcome', 'declined'), _negated=True), models.Q(('note', ''), _negated=True), _connector='OR'), name='declined_eligibility_states_why'),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.UniqueConstraint(fields=('provider', 'code'), name='plan_code_unique_per_provider'),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.CheckConstraint(condition=models.Q(('default_scheme_percent__gte', 0), ('default_scheme_percent__lte', 100)), name='plan_default_percent_is_a_percentage'),
        ),
        migrations.AddIndex(
            model_name='patientpolicy',
            index=models.Index(fields=['patient', 'is_active'], name='insurance_p_patient_68f086_idx'),
        ),
        migrations.AddConstraint(
            model_name='patientpolicy',
            constraint=models.UniqueConstraint(fields=('patient', 'plan', 'policy_number'), name='one_policy_per_patient_plan_and_number'),
        ),
        migrations.AddConstraint(
            model_name='patientpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('ends_on__isnull', True), ('ends_on__gte', models.F('starts_on')), _connector='OR'), name='policy_ends_after_it_starts'),
        ),
        migrations.AddConstraint(
            model_name='patientpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('is_dependant', False), models.Q(('relationship', ''), _negated=True), _connector='OR'), name='dependant_states_a_relationship'),
        ),
        migrations.AddConstraint(
            model_name='coveragerule',
            constraint=models.UniqueConstraint(condition=models.Q(('service__isnull', False)), fields=('plan', 'service'), name='one_rule_per_plan_and_service'),
        ),
        migrations.AddConstraint(
            model_name='coveragerule',
            constraint=models.UniqueConstraint(condition=models.Q(('category__isnull', False)), fields=('plan', 'category'), name='one_rule_per_plan_and_category'),
        ),
        migrations.AddConstraint(
            model_name='coveragerule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('category__isnull', True), ('service__isnull', False)), models.Q(('category__isnull', False), ('service__isnull', True)), _connector='OR'), name='rule_names_a_service_or_a_category_not_both'),
        ),
        migrations.AddConstraint(
            model_name='coveragerule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('basis', 'percentage'), _negated=True), ('scheme_percent__isnull', False), _connector='OR'), name='percentage_rule_states_a_percentage'),
        ),
        migrations.AddConstraint(
            model_name='coveragerule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('basis', 'fixed_copay'), _negated=True), ('patient_copay__isnull', False), _connector='OR'), name='copay_rule_states_a_copay'),
        ),
        migrations.AddConstraint(
            model_name='coveragerule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('basis', 'excluded'), _negated=True), models.Q(('exclusion_reason', ''), _negated=True), _connector='OR'), name='exclusion_states_a_reason'),
        ),
        migrations.AddIndex(
            model_name='preauthorisation',
            index=models.Index(fields=['patient', '-requested_at'], name='insurance_p_patient_1afae0_idx'),
        ),
        migrations.AddConstraint(
            model_name='preauthorisation',
            constraint=models.UniqueConstraint(condition=models.Q(('reference', ''), _negated=True), fields=('reference',), name='preauthorisation_reference_unique'),
        ),
        migrations.AddConstraint(
            model_name='preauthorisation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'approved'), _negated=True), models.Q(('reference', ''), _negated=True), _connector='OR'), name='approved_preauthorisation_has_a_reference'),
        ),
        migrations.AddConstraint(
            model_name='preauthorisation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'declined'), _negated=True), models.Q(('decline_reason', ''), _negated=True), _connector='OR'), name='declined_preauthorisation_states_why'),
        ),
        migrations.AddConstraint(
            model_name='chargecoverage',
            constraint=models.CheckConstraint(condition=models.Q(('scheme_amount__gte', 0), ('patient_amount__gte', 0)), name='coverage_amounts_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='chargecoverage',
            constraint=models.CheckConstraint(condition=models.Q(('rule_description', ''), _negated=True), name='coverage_explains_itself'),
        ),
        migrations.AddConstraint(
            model_name='providerpayment',
            constraint=models.UniqueConstraint(fields=('provider', 'reference'), name='one_payment_per_provider_reference'),
        ),
        migrations.AddConstraint(
            model_name='providerpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='provider_payment_is_positive'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.UniqueConstraint(fields=('payment', 'line'), name='one_allocation_per_payment_and_line'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='allocation_is_positive'),
        ),
    ]
