# Generated by Django 6.1.1 on 2026-09-07 02:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        ('patients', '0004_patient_patient_phone_trgm'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'lab test categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=40, unique=True)),
                ('ordered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent')], default='routine', max_length=10)),
                ('clinical_details', models.TextField(blank=True, help_text='Why the test was requested; the laboratory reads this.')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_orders', to='facilities.facility')),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_orders', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_orders', to='patients.patient')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_orders', to='visits.visit')),
            ],
            options={
                'ordering': ['-ordered_at'],
            },
        ),
        migrations.CreateModel(
            name='LabOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('collected', 'Specimen collected'), ('processing', 'Processing'), ('resulted', 'Resulted, awaiting verification'), ('verified', 'Verified'), ('cancelled', 'Cancelled')], default='ordered', max_length=15)),
                ('cancelled_reason', models.CharField(blank=True, max_length=255)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('laboratory_comment', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='laboratory.laborder')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_items_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_numeric', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('value_text', models.CharField(blank=True, max_length=255)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('flag', models.CharField(choices=[('normal', 'Normal'), ('low', 'Low'), ('high', 'High'), ('critical_low', 'Critically low'), ('critical_high', 'Critically high')], default='normal', max_length=15)),
                ('range_low', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('range_high', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('range_note', models.CharField(blank=True, max_length=255)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current', models.BooleanField(default=True)),
                ('amendment_reason', models.TextField(blank=True)),
                ('entered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('amends', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='amended_by', to='laboratory.labresult')),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_results_entered', to=settings.AUTH_USER_MODEL)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='laboratory.laborderitem')),
            ],
            options={
                'ordering': ['order_item', 'parameter__display_order', 'version'],
            },
        ),
        migrations.CreateModel(
            name='CriticalResultAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acknowledged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('action_taken', models.TextField()),
                ('acknowledged_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='critical_results_acknowledged', to=settings.AUTH_USER_MODEL)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acknowledgements', to='laboratory.labresult')),
            ],
            options={
                'ordering': ['-acknowledged_at'],
            },
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_system', models.CharField(blank=True, help_text='e.g. ICD-10, LOINC, ATC', max_length=64)),
                ('code', models.CharField(blank=True, max_length=64)),
                ('code_display', models.CharField(blank=True, max_length=255)),
                ('code_version', models.CharField(blank=True, help_text='Release of the code system used.', max_length=32)),
                ('name', models.CharField(max_length=200)),
                ('short_code', models.CharField(max_length=20, unique=True)),
                ('specimen_type', models.CharField(choices=[('blood', 'Blood'), ('urine', 'Urine'), ('stool', 'Stool'), ('swab', 'Swab'), ('sputum', 'Sputum'), ('csf', 'Cerebrospinal fluid'), ('other', 'Other')], default='blood', max_length=15)),
                ('specimen_requirements', models.CharField(blank=True, help_text='e.g. Fasting 8 hours; EDTA bottle', max_length=255)),
                ('turnaround_hours', models.PositiveSmallIntegerField(default=24)),
                ('is_active', models.BooleanField(default=True)),
                ('is_panel', models.BooleanField(default=False, help_text='A panel is ordered as one line and expands into members.')),
                ('panel_members', models.ManyToManyField(blank=True, related_name='panels', to='laboratory.labtest')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='laboratory.labtestcategory')),
            ],
            options={
                'ordering': ['category__display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='laborderitem',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='laboratory.labtest'),
        ),
        migrations.CreateModel(
            name='LabTestParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_system', models.CharField(blank=True, help_text='e.g. ICD-10, LOINC, ATC', max_length=64)),
                ('code', models.CharField(blank=True, max_length=64)),
                ('code_display', models.CharField(blank=True, max_length=255)),
                ('code_version', models.CharField(blank=True, help_text='Release of the code system used.', max_length=32)),
                ('name', models.CharField(max_length=120)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('value_type', models.CharField(choices=[('numeric', 'Numeric'), ('text', 'Text'), ('choice', 'Choice')], default='numeric', max_length=10)),
                ('choices_csv', models.CharField(blank=True, help_text="For choice parameters, e.g. 'Positive,Negative'", max_length=255)),
                ('decimal_places', models.PositiveSmallIntegerField(default=1)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='laboratory.labtest')),
            ],
            options={
                'ordering': ['test', 'display_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='labresult',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='laboratory.labtestparameter'),
        ),
        migrations.CreateModel(
            name='ReferenceRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('any', 'Any'), ('female', 'Female'), ('male', 'Male')], default='any', max_length=10)),
                ('min_age_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_age_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('low', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('high', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('critical_low', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('critical_high', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_ranges', to='laboratory.labtestparameter')),
            ],
            options={
                'ordering': ['parameter', 'sex', 'min_age_years'],
            },
        ),
        migrations.CreateModel(
            name='Specimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specimen_id', models.CharField(editable=False, max_length=40, unique=True)),
                ('specimen_type', models.CharField(choices=[('blood', 'Blood'), ('urine', 'Urine'), ('stool', 'Stool'), ('swab', 'Swab'), ('sputum', 'Sputum'), ('csf', 'Cerebrospinal fluid'), ('other', 'Other')], max_length=15)),
                ('collected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('condition', models.CharField(choices=[('acceptable', 'Acceptable'), ('haemolysed', 'Haemolysed'), ('insufficient', 'Insufficient volume'), ('clotted', 'Clotted')], default='acceptable', max_length=15)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('collected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specimens_collected', to=settings.AUTH_USER_MODEL)),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specimen', to='laboratory.laborderitem')),
            ],
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['patient', '-ordered_at'], name='laboratory__patient_c577be_idx'),
        ),
        migrations.AddConstraint(
            model_name='laborderitem',
            constraint=models.UniqueConstraint(fields=('order', 'test'), name='test_once_per_order'),
        ),
        migrations.AddConstraint(
            model_name='labtestparameter',
            constraint=models.UniqueConstraint(fields=('test', 'name'), name='parameter_unique_per_test'),
        ),
        migrations.AddConstraint(
            model_name='labresult',
            constraint=models.UniqueConstraint(fields=('order_item', 'parameter', 'version'), name='result_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='labresult',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('order_item', 'parameter'), name='one_current_result_per_parameter'),
        ),
        migrations.AddConstraint(
            model_name='labresult',
            constraint=models.CheckConstraint(condition=models.Q(('version', 1), models.Q(('amendment_reason', ''), _negated=True), _connector='OR'), name='result_amendment_states_a_reason'),
        ),
    ]
