# Generated by Django 6.1.1 on 2026-09-07 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laborderitem',
            options={'ordering': ['order', 'id'], 'permissions': [('collect_specimen', 'Can collect and label specimens'), ('verify_labresult', 'Can verify and release laboratory results')]},
        ),
        migrations.AlterModelOptions(
            name='labresult',
            options={'ordering': ['order_item', 'parameter__display_order', 'version'], 'permissions': [('amend_labresult', 'Can amend a verified laboratory result'), ('acknowledge_critical_result', 'Can acknowledge a critical result')]},
        ),
    ]
