# Generated by Django 6.1.1 on 2026-09-07 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('laboratory', '0002_alter_laborderitem_options_alter_labresult_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Billed through this service.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_tests', to='billing.service'),
        ),
    ]
