# Generated by Django 6.1.1 on 2026-09-07 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
        ('inpatient', '0001_initial'),
        ('laboratory', '0003_labtest_service'),
        ('patients', '0004_patient_patient_phone_trgm'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='laborder',
            name='admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_orders', to='inpatient.admission'),
        ),
        migrations.AlterField(
            model_name='laborder',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_orders', to='visits.visit'),
        ),
        migrations.AddConstraint(
            model_name='laborder',
            constraint=models.CheckConstraint(condition=models.Q(('visit__isnull', False), ('admission__isnull', False), _connector='OR'), name='lab_order_belongs_to_a_visit_or_an_admission'),
        ),
    ]
