# Generated by Django 6.1.1 on 2026-09-07 20:39

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0002_remove_invoice_one_draft_invoice_per_visit'),
        ('clinical', '0002_alter_vitalsigns_weight_kg'),
        ('facilities', '0001_initial'),
        ('patients', '0004_patient_patient_phone_trgm'),
        ('pharmacy', '0002_medication_selling_price'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # First, and not optional. The exclusion constraint on bed occupancy
        # indexes a bigint foreign key alongside a range, and a bigint has no
        # default operator class for GiST — without btree_gist the constraint
        # cannot be created at all ("data type bigint has no default operator
        # class for access method gist").
        BtreeGistExtension(),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('service_state', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('cleaning', 'Being cleaned'), ('maintenance', 'Unavailable for maintenance')], default='available', max_length=15)),
                ('state_note', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['room', 'code'],
            },
        ),
        migrations.CreateModel(
            name='EscalationThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement', models.CharField(choices=[('temperature_c', 'Temperature (°C)'), ('systolic_bp', 'Systolic BP (mmHg)'), ('diastolic_bp', 'Diastolic BP (mmHg)'), ('pulse_bpm', 'Pulse (bpm)'), ('respiratory_rate', 'Respiratory rate'), ('oxygen_saturation', 'Oxygen saturation (%)'), ('blood_glucose_mmol', 'Blood glucose (mmol/L)')], max_length=30)),
                ('low', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('high', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('instruction', models.CharField(blank=True, help_text='What the nurse should do. Shown with the alert.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['ward', 'measurement'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['ward', 'code'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('working_diagnosis', models.CharField(max_length=255)),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent')], default='routine', max_length=10)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Awaiting a bed'), ('admitted', 'Admitted'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.CharField(blank=True, max_length=255)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admission_requests_decided', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admission_requests', to='facilities.facility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admission_requests', to='patients.patient')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admission_requests_made', to=settings.AUTH_USER_MODEL)),
                ('responsible_consultant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admission_requests_under_care', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(blank=True, help_text='The attendance the request came out of, where there was one.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admission_requests', to='visits.visit')),
            ],
            options={
                'ordering': ['-priority', 'requested_at'],
                'permissions': [('decide_admissionrequest', 'Can accept or decline an admission request')],
            },
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(editable=False, max_length=40, unique=True)),
                ('admission_reason', models.TextField()),
                ('admission_diagnosis', models.CharField(max_length=255)),
                ('admitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('admitted', 'Admitted'), ('discharge_planned', 'Discharge planned'), ('discharged', 'Discharged')], default='admitted', max_length=20)),
                ('expected_discharge_date', models.DateField(blank=True, null=True)),
                ('discharge_destination', models.CharField(blank=True, choices=[('home', 'Home'), ('transferred', 'Transferred to another facility'), ('absconded', 'Absconded'), ('died', 'Died')], max_length=15)),
                ('discharge_plan_notes', models.TextField(blank=True)),
                ('discharged_at', models.DateTimeField(blank=True, null=True)),
                ('discharge_diagnosis', models.CharField(blank=True, max_length=255)),
                ('follow_up_instructions', models.TextField(blank=True)),
                ('billing_override_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions_made', to=settings.AUTH_USER_MODEL)),
                ('discharged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discharges_completed', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='facilities.facility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='patients.patient')),
                ('responsible_consultant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patients_under_care', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='visits.visit')),
                ('request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admission', to='inpatient.admissionrequest')),
            ],
            options={
                'ordering': ['-admitted_at'],
                'permissions': [('admit_patient', 'Can admit a patient and allocate a bed'), ('transfer_patient', 'Can move an inpatient between beds or wards'), ('plan_discharge', 'Can record a discharge plan'), ('discharge_patient', 'Can complete a discharge'), ('override_discharge_billing', 'Can discharge despite an unpaid balance')],
            },
        ),
        migrations.CreateModel(
            name='BedOccupancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ('reason_ended', models.CharField(blank=True, max_length=120)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occupancies', to='inpatient.admission')),
                ('allocated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bed_allocations', to=settings.AUTH_USER_MODEL)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occupancies', to='inpatient.bed')),
                ('ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bed_releases', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bed_occupancies', to='patients.patient')),
            ],
            options={
                'verbose_name_plural': 'bed occupancies',
                'ordering': ['bed', 'period'],
            },
        ),
        migrations.CreateModel(
            name='BedTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('moved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='inpatient.admission')),
                ('authorised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_authorised', to=settings.AUTH_USER_MODEL)),
                ('from_occupancy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='inpatient.bedoccupancy')),
                ('to_occupancy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='inpatient.bedoccupancy')),
            ],
            options={
                'ordering': ['-moved_at'],
            },
        ),
        migrations.CreateModel(
            name='Escalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement', models.CharField(max_length=30)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('direction', models.CharField(choices=[('low', 'Below the low bound'), ('high', 'Above the high bound')], max_length=4)),
                ('breached_bound', models.DecimalField(decimal_places=2, max_digits=8)),
                ('instruction', models.CharField(blank=True, max_length=255)),
                ('raised_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('action_taken', models.TextField(blank=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='escalations_acknowledged', to=settings.AUTH_USER_MODEL)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escalations', to='inpatient.admission')),
                ('escalated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='escalations_received', to=settings.AUTH_USER_MODEL)),
                ('observations', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escalations', to='clinical.vitalsigns')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escalations', to='patients.patient')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escalations_raised', to=settings.AUTH_USER_MODEL)),
                ('threshold', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalations', to='inpatient.escalationthreshold')),
            ],
            options={
                'ordering': ['-raised_at'],
            },
        ),
        migrations.CreateModel(
            name='FluidBalanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('intake', 'Intake'), ('output', 'Output')], max_length=6)),
                ('route', models.CharField(choices=[('oral', 'Oral'), ('iv', 'Intravenous'), ('ng', 'Nasogastric'), ('other_in', 'Other intake'), ('urine', 'Urine'), ('vomit', 'Vomit'), ('drain', 'Drain'), ('stool', 'Stool'), ('other_out', 'Other output')], max_length=10)),
                ('volume_ml', models.PositiveIntegerField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fluid_entries', to='inpatient.admission')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fluid_entries', to='patients.patient')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fluid_entries_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'fluid balance entries',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='NursingAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('early', 'Early'), ('late', 'Late'), ('night', 'Night')], max_length=10)),
                ('consciousness', models.CharField(choices=[('alert', 'Alert'), ('voice', 'Responds to voice'), ('pain', 'Responds to pain'), ('unresponsive', 'Unresponsive')], default='alert', max_length=12)),
                ('mobility', models.CharField(choices=[('independent', 'Independent'), ('assisted', 'Needs assistance'), ('bedbound', 'Bedbound')], default='independent', max_length=12)),
                ('falls_risk', models.BooleanField(default=False)),
                ('pressure_area_concern', models.BooleanField(default=False)),
                ('eating_and_drinking', models.CharField(blank=True, max_length=255)),
                ('continence', models.CharField(blank=True, max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nursing_assessments', to='inpatient.admission')),
                ('observations', models.OneToOneField(blank=True, help_text='The observations taken as part of this assessment.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nursing_assessment', to='clinical.vitalsigns')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nursing_assessments', to='patients.patient')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nursing_assessments_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
                'permissions': [('escalate_observation', 'Can raise and acknowledge an observation escalation')],
            },
        ),
        migrations.CreateModel(
            name='NursingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('early', 'Early'), ('late', 'Late'), ('night', 'Night')], max_length=10)),
                ('note', models.TextField()),
                ('correction_reason', models.CharField(blank=True, max_length=255)),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nursing_notes', to='inpatient.admission')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nursing_notes_written', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nursing_notes', to='patients.patient')),
                ('supersedes', models.OneToOneField(blank=True, help_text='The note this one corrects. The original stays legible.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correction', to='inpatient.nursingnote')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddField(
            model_name='bed',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beds', to='inpatient.room'),
        ),
        migrations.CreateModel(
            name='ScheduledDose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_at', models.DateTimeField(db_index=True)),
                ('sequence', models.PositiveIntegerField(help_text='Position in the course, from 1.')),
                ('dose', models.DecimalField(decimal_places=3, max_digits=10)),
                ('dose_unit', models.CharField(max_length=20)),
                ('route', models.CharField(max_length=15)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_reason', models.CharField(blank=True, max_length=255)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_doses', to='inpatient.admission')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_doses', to='patients.patient')),
                ('prescription_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_doses', to='pharmacy.prescriptionitem')),
            ],
            options={
                'ordering': ['due_at', 'prescription_item_id'],
            },
        ),
        migrations.CreateModel(
            name='MedicationAdministration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('administered', 'Administered'), ('missed', 'Missed'), ('delayed', 'Given late'), ('refused', 'Refused by patient'), ('withheld', 'Withheld'), ('discontinued', 'Discontinued')], max_length=15)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('administered_at', models.DateTimeField(blank=True, help_text='When the drug actually reached the patient.', null=True)),
                ('dose_given', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('dose_unit', models.CharField(blank=True, max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('override_reason', models.TextField(blank=True)),
                ('administered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administrations_given', to=settings.AUTH_USER_MODEL)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administrations', to='inpatient.admission')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='administrations', to='pharmacy.stockbatch')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administrations', to='patients.patient')),
                ('scheduled_dose', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administrations', to='inpatient.scheduleddose')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=20)),
                ('ward_type', models.CharField(choices=[('general', 'General'), ('male', 'Male'), ('female', 'Female'), ('paediatric', 'Paediatric'), ('maternity', 'Maternity'), ('intensive', 'Intensive care'), ('isolation', 'Isolation')], default='general', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wards', to='facilities.department')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wards', to='facilities.facility')),
                ('nightly_service', models.ForeignKey(blank=True, help_text='Service used to charge each bed night.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wards', to='billing.service')),
            ],
            options={
                'ordering': ['facility', 'name'],
                'permissions': [('manage_beds', 'Can change bed availability and take beds out of service')],
            },
        ),
        migrations.AddField(
            model_name='room',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='inpatient.ward'),
        ),
        migrations.AddField(
            model_name='escalationthreshold',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_thresholds', to='inpatient.ward'),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='ward',
            field=models.ForeignKey(help_text='Where the requesting clinician believes the patient should go.', on_delete=django.db.models.deletion.PROTECT, related_name='admission_requests', to='inpatient.ward'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['facility', 'status', '-admitted_at'], name='inpatient_a_facilit_37c054_idx'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['patient', '-admitted_at'], name='inpatient_a_patient_0aa045_idx'),
        ),
        migrations.AddConstraint(
            model_name='admission',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'discharged'), _negated=True), fields=('patient',), name='one_open_admission_per_patient'),
        ),
        migrations.AddConstraint(
            model_name='admission',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'discharged'), _negated=True), models.Q(('discharged_at__isnull', False), models.Q(('discharge_diagnosis', ''), _negated=True)), _connector='OR'), name='discharged_admission_is_complete'),
        ),
        migrations.AddIndex(
            model_name='bedoccupancy',
            index=models.Index(fields=['admission'], name='inpatient_b_admissi_b87713_idx'),
        ),
        migrations.AddConstraint(
            model_name='bedoccupancy',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('period', '&&'), ('bed', '=')], name='one_patient_per_bed_at_a_time'),
        ),
        migrations.AddConstraint(
            model_name='bedoccupancy',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('period', '&&'), ('patient', '=')], name='one_bed_per_patient_at_a_time'),
        ),
        migrations.AddIndex(
            model_name='escalation',
            index=models.Index(fields=['admission', '-raised_at'], name='inpatient_e_admissi_ede9fe_idx'),
        ),
        migrations.AddIndex(
            model_name='escalation',
            index=models.Index(condition=models.Q(('acknowledged_at__isnull', True)), fields=['-raised_at'], name='outstanding_escalations'),
        ),
        migrations.AddConstraint(
            model_name='escalation',
            constraint=models.CheckConstraint(condition=models.Q(('acknowledged_at__isnull', True), models.Q(('acknowledged_by__isnull', False), models.Q(('action_taken', ''), _negated=True)), _connector='OR'), name='acknowledged_escalation_says_who_and_what'),
        ),
        migrations.AddIndex(
            model_name='fluidbalanceentry',
            index=models.Index(fields=['admission', '-recorded_at'], name='inpatient_f_admissi_df3e4b_idx'),
        ),
        migrations.AddConstraint(
            model_name='fluidbalanceentry',
            constraint=models.CheckConstraint(condition=models.Q(('volume_ml__gt', 0)), name='fluid_volume_is_positive'),
        ),
        migrations.AddConstraint(
            model_name='fluidbalanceentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('direction', 'intake'), ('route__in', ['oral', 'iv', 'ng', 'other_in'])), models.Q(('direction', 'output'), ('route__in', ['urine', 'vomit', 'drain', 'stool', 'other_out'])), _connector='OR'), name='fluid_route_matches_direction'),
        ),
        migrations.AddIndex(
            model_name='nursingassessment',
            index=models.Index(fields=['admission', '-recorded_at'], name='inpatient_n_admissi_26e3dd_idx'),
        ),
        migrations.AddIndex(
            model_name='nursingnote',
            index=models.Index(fields=['admission', '-recorded_at'], name='inpatient_n_admissi_abe7e3_idx'),
        ),
        migrations.AddConstraint(
            model_name='nursingnote',
            constraint=models.CheckConstraint(condition=models.Q(('supersedes__isnull', True), models.Q(('correction_reason', ''), _negated=True), _connector='OR'), name='correcting_note_states_a_reason'),
        ),
        migrations.AddConstraint(
            model_name='bed',
            constraint=models.UniqueConstraint(fields=('room', 'code'), name='bed_code_unique_per_room'),
        ),
        migrations.AddIndex(
            model_name='scheduleddose',
            index=models.Index(fields=['admission', 'due_at'], name='inpatient_s_admissi_5970b0_idx'),
        ),
        migrations.AddConstraint(
            model_name='scheduleddose',
            constraint=models.UniqueConstraint(fields=('prescription_item', 'due_at'), name='one_dose_per_item_per_due_time'),
        ),
        migrations.AddConstraint(
            model_name='scheduleddose',
            constraint=models.CheckConstraint(condition=models.Q(('cancelled_at__isnull', True), models.Q(('cancelled_reason', ''), _negated=True), _connector='OR'), name='cancelled_dose_states_a_reason'),
        ),
        migrations.AddIndex(
            model_name='medicationadministration',
            index=models.Index(fields=['admission', '-recorded_at'], name='inpatient_m_admissi_078fea_idx'),
        ),
        migrations.AddConstraint(
            model_name='medicationadministration',
            constraint=models.UniqueConstraint(fields=('scheduled_dose',), name='one_outcome_per_scheduled_dose'),
        ),
        migrations.AddConstraint(
            model_name='medicationadministration',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('state__in', ['missed', 'refused', 'withheld', 'discontinued']), _negated=True), models.Q(('reason', ''), _negated=True), _connector='OR'), name='unadministered_dose_states_a_reason'),
        ),
        migrations.AddConstraint(
            model_name='medicationadministration',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('state__in', ['administered', 'delayed']), _negated=True), ('administered_at__isnull', False), _connector='OR'), name='administered_dose_records_when'),
        ),
        migrations.AddConstraint(
            model_name='ward',
            constraint=models.UniqueConstraint(fields=('facility', 'code'), name='ward_code_unique_per_facility'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('ward', 'code'), name='room_code_unique_per_ward'),
        ),
        migrations.AddConstraint(
            model_name='escalationthreshold',
            constraint=models.UniqueConstraint(fields=('ward', 'measurement'), name='one_threshold_per_ward_measurement'),
        ),
        migrations.AddConstraint(
            model_name='escalationthreshold',
            constraint=models.CheckConstraint(condition=models.Q(('low__isnull', False), ('high__isnull', False), _connector='OR'), name='threshold_bounds_at_least_one'),
        ),
        migrations.AddIndex(
            model_name='admissionrequest',
            index=models.Index(fields=['ward', 'status', 'requested_at'], name='inpatient_a_ward_id_707b39_idx'),
        ),
        migrations.AddConstraint(
            model_name='admissionrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'declined'), _negated=True), models.Q(('decline_reason', ''), _negated=True), _connector='OR'), name='declined_request_states_a_reason'),
        ),
    ]
