# Generated by Django 6.1.1 on 2026-09-07 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inpatient', '0002_nursing_note_append_only'),
        ('patients', '0004_patient_patient_phone_trgm'),
        ('pharmacy', '0003_alter_prescription_options_prescription_admission_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='scheduleddose',
            index=models.Index(condition=models.Q(('cancelled_at__isnull', True)), fields=['admission', 'due_at'], name='outstanding_doses_by_admission'),
        ),
    ]
