# Generated by Django 6.1.1 on 2026-09-10 04:25

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0005_alter_cashiersession_options'),
        ('facilities', '0001_initial'),
        ('inpatient', '0003_scheduleddose_outstanding_doses_by_admission'),
        ('inventory', '0003_remove_purchaserequest_decided_request_names_who_decided_and_more'),
        ('patients', '0004_patient_patient_phone_trgm'),
        ('pharmacy', '0003_alter_prescription_options_prescription_admission_and_more'),
        ('visits', '0002_alter_visit_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'procedure categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PerformedProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('outcome', models.CharField(choices=[('completed', 'Completed'), ('abandoned', 'Abandoned before completion')], default='completed', max_length=12)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_billed', models.BooleanField(default=False)),
                ('lead_clinician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedures_led', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedures_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OperationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('performed', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='note', to='procedures.performedprocedure')),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('typical_duration_minutes', models.PositiveSmallIntegerField(default=30, help_text='Used to size a theatre booking, not to enforce one.')),
                ('requires_theatre', models.BooleanField(default=False)),
                ('requires_consent', models.BooleanField(default=True, help_text='Whether written consent is required before it may be performed.')),
                ('requires_anaesthesia', models.BooleanField(default=False)),
                ('preparation', models.TextField(blank=True, help_text='What the patient is told beforehand.')),
                ('is_active', models.BooleanField(default=True)),
                ('billing_service', models.ForeignKey(blank=True, help_text='What this bills as. Without one it is recorded but not charged.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procedures', to='billing.service')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedures', to='procedures.procedurecategory')),
            ],
            options={
                'ordering': ['category__display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProcedureConsumableUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedure_consumption', to='inventory.inventoryitem')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedure_uses', to='inventory.stockmovement')),
                ('performed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumables_used', to='procedures.performedprocedure')),
            ],
            options={
                'ordering': ['performed', 'item__name'],
            },
        ),
        migrations.CreateModel(
            name='ProcedureMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose', models.CharField(max_length=80)),
                ('route', models.CharField(max_length=30)),
                ('given_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('given_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedure_medications_given', to=settings.AUTH_USER_MODEL)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedure_administrations', to='pharmacy.medication')),
                ('performed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='procedures.performedprocedure')),
            ],
            options={
                'ordering': ['performed', 'given_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcedureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=30, unique=True)),
                ('indication', models.TextField(help_text='Why this patient needs this procedure.')),
                ('urgency', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], default='routine', max_length=10)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('scheduled', 'Scheduled'), ('performed', 'Performed'), ('cancelled', 'Cancelled')], default='requested', max_length=12)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=255)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procedure_requests', to='inpatient.admission')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedure_requests', to='facilities.facility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedure_requests', to='patients.patient')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='procedures.procedure')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedure_requests', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procedure_requests', to='visits.visit')),
            ],
            options={
                'ordering': ['-requested_at', '-id'],
                'permissions': [('request_procedure', 'Can request a procedure'), ('schedule_procedure', 'Can book a theatre'), ('perform_procedure', 'Can record a procedure as performed'), ('record_consent', "Can record a patient's consent"), ('amend_operation_note', 'Can amend an operation note')],
            },
        ),
        migrations.AddField(
            model_name='performedprocedure',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='performed', to='procedures.procedurerequest'),
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_by', models.CharField(choices=[('patient', 'The patient'), ('next_of_kin', 'Next of kin or legal guardian'), ('two_doctors', 'Two doctors, patient unable to consent')], default='patient', max_length=15)),
                ('given_by_name', models.CharField(blank=True, help_text='Required where somebody other than the patient consented.', max_length=200)),
                ('relationship', models.CharField(blank=True, max_length=80)),
                ('risks_discussed', models.TextField(help_text='What was explained: the procedure, its risks, and the alternatives.')),
                ('interpreter_used', models.BooleanField(default=False)),
                ('interpreter_name', models.CharField(blank=True, max_length=200)),
                ('taken_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawal_reason', models.CharField(blank=True, max_length=255)),
                ('taken_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consents_taken', to=settings.AUTH_USER_MODEL)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consent', to='procedures.procedurerequest')),
            ],
        ),
        migrations.CreateModel(
            name='ProcedureTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('surgeon', 'Surgeon'), ('assistant', 'Assistant'), ('anaesthetist', 'Anaesthetist'), ('scrub_nurse', 'Scrub nurse'), ('circulating_nurse', 'Circulating nurse'), ('other', 'Other')], max_length=20)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedure_team_roles', to=settings.AUTH_USER_MODEL)),
                ('performed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='procedures.performedprocedure')),
            ],
            options={
                'ordering': ['performed', 'role'],
            },
        ),
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('out_of_service_note', models.CharField(blank=True, max_length=255)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='theatres', to='facilities.facility')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theatres', to='inventory.store')),
            ],
            options={
                'ordering': ['facility', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TheatreBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', django.contrib.postgres.fields.ranges.DateTimeRangeField(help_text='When the theatre is held.')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=12)),
                ('booked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=255)),
                ('anaesthetist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='theatre_bookings_anaesthetised', to=settings.AUTH_USER_MODEL)),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='theatre_bookings_made', to=settings.AUTH_USER_MODEL)),
                ('lead_surgeon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='theatre_bookings_led', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='procedures.procedurerequest')),
                ('theatre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='procedures.theatre')),
            ],
            options={
                'ordering': ['period'],
            },
        ),
        migrations.AddField(
            model_name='performedprocedure',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='performed', to='procedures.theatrebooking'),
        ),
        migrations.CreateModel(
            name='OperationNoteVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('is_current', models.BooleanField(default=True)),
                ('findings', models.TextField()),
                ('procedure_performed', models.TextField(help_text='What was actually done, which is not always what was requested.')),
                ('closure', models.TextField(blank=True)),
                ('estimated_blood_loss_ml', models.PositiveIntegerField(blank=True, null=True)),
                ('specimens_taken', models.CharField(blank=True, max_length=255)),
                ('complications', models.TextField(blank=True)),
                ('post_operative_instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('amendment_reason', models.TextField(blank=True, help_text='Required on every version after the first.')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operation_note_versions', to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='procedures.operationnote')),
            ],
            options={
                'ordering': ['note', '-version_number'],
                'constraints': [models.UniqueConstraint(fields=('note', 'version_number'), name='one_version_number_per_note'), models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('note',), name='one_current_version_per_note'), models.CheckConstraint(condition=models.Q(('findings', ''), _negated=True), name='operation_note_records_findings'), models.CheckConstraint(condition=models.Q(('version_number', 1), models.Q(('amendment_reason', ''), _negated=True), _connector='OR'), name='amended_note_states_a_reason')],
            },
        ),
        migrations.CreateModel(
            name='ProcedureConsumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedure_uses', to='inventory.inventoryitem')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumables', to='procedures.procedure')),
            ],
            options={
                'ordering': ['procedure', 'item__name'],
                'constraints': [models.UniqueConstraint(fields=('procedure', 'item'), name='one_consumable_line_per_procedure')],
            },
        ),
        migrations.AddConstraint(
            model_name='procedurerequest',
            constraint=models.CheckConstraint(condition=models.Q(('indication', ''), _negated=True), name='procedure_request_states_an_indication'),
        ),
        migrations.AddConstraint(
            model_name='procedurerequest',
            constraint=models.CheckConstraint(condition=models.Q(('visit__isnull', False), ('admission__isnull', False), _connector='OR'), name='procedure_request_belongs_to_an_episode'),
        ),
        migrations.AddConstraint(
            model_name='procedurerequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'cancelled'), _negated=True), models.Q(('cancellation_reason', ''), _negated=True), _connector='OR'), name='cancelled_procedure_says_why'),
        ),
        migrations.AddConstraint(
            model_name='consent',
            constraint=models.CheckConstraint(condition=models.Q(('risks_discussed', ''), _negated=True), name='consent_records_what_was_discussed'),
        ),
        migrations.AddConstraint(
            model_name='consent',
            constraint=models.CheckConstraint(condition=models.Q(('given_by', 'patient'), models.Q(('given_by_name', ''), _negated=True), _connector='OR'), name='proxy_consent_names_the_person'),
        ),
        migrations.AddConstraint(
            model_name='procedureteammember',
            constraint=models.UniqueConstraint(fields=('performed', 'member', 'role'), name='one_role_per_person_per_procedure'),
        ),
        migrations.AddConstraint(
            model_name='theatre',
            constraint=models.UniqueConstraint(fields=('facility', 'code'), name='theatre_code_unique_per_facility'),
        ),
        migrations.AddConstraint(
            model_name='theatrebooking',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status__in', ['scheduled', 'in_progress', 'completed'])), expressions=[('theatre', '='), ('period', '&&')], name='one_operation_per_theatre_at_a_time'),
        ),
        migrations.AddConstraint(
            model_name='performedprocedure',
            constraint=models.CheckConstraint(condition=models.Q(('finished_at__gt', models.F('started_at'))), name='procedure_finishes_after_it_starts'),
        ),
    ]
