# Generated by Django 6.1.1 on 2026-09-10 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'report access',
                'permissions': [('view_reports', 'Can open the reports section')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
