# Generated by Django 6.1.1 on 2026-09-10 04:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        ('inpatient', '0003_scheduleddose_outstanding_doses_by_admission'),
        ('patients', '0005_patient_is_unidentified'),
        ('procedures', '0001_initial'),
        ('visits', '0003_triagelevel_emergencyepisode_triageassessment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregnancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_menstrual_period', models.DateField(blank=True, null=True)),
                ('estimated_delivery_date', models.DateField()),
                ('edd_basis', models.CharField(choices=[('lmp', 'Last menstrual period'), ('ultrasound', 'Ultrasound dating scan'), ('examination', 'Clinical examination'), ('uncertain', 'Uncertain')], max_length=12)),
                ('edd_basis_note', models.CharField(blank=True, help_text='Which scan, at what gestation — so a later revision can be judged.', max_length=255)),
                ('gravida', models.PositiveSmallIntegerField(default=1, help_text='Total pregnancies including this one.')),
                ('parity', models.PositiveSmallIntegerField(default=0, help_text='Births after 28 weeks.')),
                ('previous_losses', models.PositiveSmallIntegerField(default=0)),
                ('risk_factors', models.TextField(blank=True, help_text='Recorded by the clinician. This software does not score risk.')),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('delivered', 'Delivered'), ('ended', 'Ended before delivery'), ('transferred', 'Care transferred out')], default='ongoing', max_length=12)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('ended_reason', models.CharField(blank=True, max_length=255)),
                ('booked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pregnancies_booked', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pregnancies', to='facilities.facility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pregnancies', to='patients.patient')),
            ],
            options={
                'verbose_name_plural': 'pregnancies',
                'ordering': ['-booked_at', '-id'],
                'permissions': [('book_pregnancy', 'Can book a pregnancy'), ('record_antenatal_visit', 'Can record an antenatal visit'), ('record_delivery', 'Can record a delivery')],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered_at', models.DateTimeField()),
                ('mode', models.CharField(choices=[('svd', 'Spontaneous vaginal delivery'), ('assisted', 'Assisted vaginal delivery'), ('lscs_elective', 'Caesarean section, elective'), ('lscs_emergency', 'Caesarean section, emergency')], max_length=15)),
                ('onset_of_labour', models.CharField(blank=True, max_length=40)),
                ('duration_of_labour_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_blood_loss_ml', models.PositiveIntegerField(blank=True, null=True)),
                ('perineal_tear', models.CharField(blank=True, max_length=40)),
                ('complications', models.TextField(blank=True)),
                ('placenta_complete', models.BooleanField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='inpatient.admission')),
                ('delivered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries_attended', to=settings.AUTH_USER_MODEL)),
                ('procedure', models.OneToOneField(blank=True, help_text='Where it was a caesarean, the theatre record of it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery', to='procedures.performedprocedure')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries_recorded', to=settings.AUTH_USER_MODEL)),
                ('pregnancy', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='delivery', to='maternity.pregnancy')),
            ],
            options={
                'verbose_name_plural': 'deliveries',
                'ordering': ['-delivered_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AntenatalVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField()),
                ('seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('gestation_weeks', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('systolic_bp', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('diastolic_bp', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fundal_height_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fetal_heart_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('presentation', models.CharField(blank=True, max_length=40)),
                ('urine_protein', models.CharField(blank=True, max_length=20)),
                ('urine_glucose', models.CharField(blank=True, max_length=20)),
                ('haemoglobin', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('notes', models.TextField(blank=True)),
                ('next_appointment', models.DateField(blank=True, null=True)),
                ('seen_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='antenatal_visits', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='antenatal_visits', to='visits.visit')),
                ('pregnancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antenatal_visits', to='maternity.pregnancy')),
            ],
            options={
                'ordering': ['pregnancy', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='Baby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_order', models.PositiveSmallIntegerField(default=1, help_text='1 for a singleton; 1 and 2 for twins.')),
                ('outcome', models.CharField(choices=[('live', 'Live birth'), ('stillbirth_fresh', 'Fresh stillbirth'), ('stillbirth_macerated', 'Macerated stillbirth')], default='live', max_length=22)),
                ('birth_weight_grams', models.PositiveIntegerField(blank=True, null=True)),
                ('apgar_one_minute', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('apgar_five_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('resuscitation', models.CharField(blank=True, max_length=255)),
                ('congenital_abnormality', models.CharField(blank=True, max_length=255)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='birth_record', to='patients.patient')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='babies', to='maternity.delivery')),
            ],
            options={
                'verbose_name_plural': 'babies',
                'ordering': ['delivery', 'birth_order'],
                'constraints': [models.UniqueConstraint(fields=('delivery', 'birth_order'), name='one_baby_per_birth_order_per_delivery'), models.CheckConstraint(condition=models.Q(('apgar_one_minute__lte', 10), ('apgar_one_minute__isnull', True), _connector='OR'), name='apgar_one_is_out_of_ten'), models.CheckConstraint(condition=models.Q(('apgar_five_minutes__lte', 10), ('apgar_five_minutes__isnull', True), _connector='OR'), name='apgar_five_is_out_of_ten')],
            },
        ),
        migrations.AddConstraint(
            model_name='pregnancy',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ongoing')), fields=('patient',), name='one_ongoing_pregnancy_per_patient'),
        ),
        migrations.AddConstraint(
            model_name='pregnancy',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'ongoing'), ('ended_at__isnull', False), ('status', 'delivered'), _connector='OR'), name='closed_pregnancy_has_an_end'),
        ),
        migrations.AddConstraint(
            model_name='antenatalvisit',
            constraint=models.UniqueConstraint(fields=('pregnancy', 'sequence'), name='one_antenatal_visit_per_sequence'),
        ),
    ]
