# Generated by Django 6.1.1 on 2026-09-07 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('outcome', models.CharField(choices=[('allowed', 'Allowed'), ('denied', 'Denied')], default='allowed', max_length=10)),
                ('actor_email', models.CharField(blank=True, help_text='Snapshot, so the row reads correctly later.', max_length=254)),
                ('resource_type', models.CharField(blank=True, db_index=True, max_length=100)),
                ('resource_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='{"before": {...}, "after": {...}}')),
                ('reason', models.TextField(blank=True)),
                ('request_id', models.CharField(blank=True, max_length=36)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('prev_hash', models.CharField(max_length=64)),
                ('row_hash', models.CharField(max_length=64, unique=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='facilities.facility')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['resource_type', 'resource_id'], name='audit_audit_resourc_2ab5ff_idx')],
            },
        ),
    ]
