# Generated by Django 6.1.1 on 2026-09-07 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_append_only_trigger'),
        ('patients', '0002_trigram_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='patient',
            field=models.ForeignKey(blank=True, help_text='Which patient this action concerned, where one applies.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='patients.patient'),
        ),
    ]
