# Generated by Django 6.1.1 on 2026-09-07 02:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0002_alter_vitalsigns_weight_kg'),
        ('facilities', '0001_initial'),
        ('patients', '0004_patient_patient_phone_trgm'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_system', models.CharField(blank=True, help_text='e.g. ICD-10, LOINC, ATC', max_length=64)),
                ('code', models.CharField(blank=True, max_length=64)),
                ('code_display', models.CharField(blank=True, max_length=255)),
                ('code_version', models.CharField(blank=True, help_text='Release of the code system used.', max_length=32)),
                ('generic_name', models.CharField(max_length=200)),
                ('brand_name', models.CharField(blank=True, max_length=200)),
                ('strength', models.CharField(help_text='e.g. 500 mg, 125 mg/5 mL', max_length=60)),
                ('dosage_form', models.CharField(help_text='e.g. tablet, suspension', max_length=60)),
                ('default_route', models.CharField(choices=[('oral', 'Oral'), ('iv', 'Intravenous'), ('im', 'Intramuscular'), ('sc', 'Subcutaneous'), ('topical', 'Topical'), ('rectal', 'Rectal'), ('inhaled', 'Inhaled'), ('ophthalmic', 'Ophthalmic')], default='oral', max_length=15)),
                ('dispensing_unit', models.CharField(default='tablet', max_length=30)),
                ('ingredients_csv', models.CharField(blank=True, help_text='Active ingredients, comma separated. Used for allergy matching.', max_length=400)),
                ('atc_class', models.CharField(blank=True, help_text='ATC class prefix used for therapeutic-duplication checks.', max_length=20)),
                ('avoid_in_pregnancy', models.BooleanField(default=False)),
                ('avoid_in_renal_impairment', models.BooleanField(default=False)),
                ('paediatric_caution', models.BooleanField(default=False)),
                ('caution_note', models.CharField(blank=True, max_length=255)),
                ('reorder_level', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['generic_name', 'strength'],
            },
        ),
        migrations.CreateModel(
            name='MedicationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'medication categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DoseRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(choices=[('oral', 'Oral'), ('iv', 'Intravenous'), ('im', 'Intramuscular'), ('sc', 'Subcutaneous'), ('topical', 'Topical'), ('rectal', 'Rectal'), ('inhaled', 'Inhaled'), ('ophthalmic', 'Ophthalmic')], max_length=15)),
                ('min_age_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_age_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('min_single_dose', models.DecimalField(decimal_places=3, max_digits=10)),
                ('max_single_dose', models.DecimalField(decimal_places=3, max_digits=10)),
                ('dose_unit', models.CharField(default='mg', max_length=20)),
                ('max_daily_dose', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dose_ranges', to='pharmacy.medication')),
            ],
            options={
                'ordering': ['medication', 'route', 'min_age_years'],
            },
        ),
        migrations.CreateModel(
            name='ContraindicationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_keyword', models.CharField(help_text="Matched against the patient's recorded chronic conditions.", max_length=100)),
                ('severity', models.CharField(choices=[('advisory', 'Advisory'), ('warning', 'Warning')], default='warning', max_length=10)),
                ('note', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('maintained_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contraindications', to='pharmacy.medication')),
            ],
        ),
        migrations.AddField(
            model_name='medication',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medications', to='pharmacy.medicationcategory'),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_number', models.CharField(editable=False, max_length=40, unique=True)),
                ('prescribed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('active', 'Active'), ('partially_dispensed', 'Partially dispensed'), ('dispensed', 'Dispensed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='clinical.encounter')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='facilities.facility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='patients.patient')),
                ('prescribed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='visits.visit')),
            ],
            options={
                'ordering': ['-prescribed_at'],
                'permissions': [('dispense_medication', 'Can dispense medication'), ('override_safety_warning', 'Can prescribe despite a safety warning')],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose', models.DecimalField(decimal_places=3, max_digits=10)),
                ('dose_unit', models.CharField(default='mg', max_length=20)),
                ('route', models.CharField(choices=[('oral', 'Oral'), ('iv', 'Intravenous'), ('im', 'Intramuscular'), ('sc', 'Subcutaneous'), ('topical', 'Topical'), ('rectal', 'Rectal'), ('inhaled', 'Inhaled'), ('ophthalmic', 'Ophthalmic')], max_length=15)),
                ('frequency_per_day', models.PositiveSmallIntegerField(default=3)),
                ('duration_days', models.PositiveSmallIntegerField(default=5)),
                ('quantity_prescribed', models.PositiveIntegerField()),
                ('quantity_dispensed', models.PositiveIntegerField(default=0)),
                ('instructions', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('prescribed', 'Prescribed'), ('partially_dispensed', 'Partially dispensed'), ('dispensed', 'Dispensed'), ('cancelled', 'Cancelled')], default='prescribed', max_length=20)),
                ('cancelled_reason', models.CharField(blank=True, max_length=255)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescription_items', to='pharmacy.medication')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.prescription')),
            ],
            options={
                'ordering': ['prescription', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SafetyOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning_kind', models.CharField(max_length=40)),
                ('warning_detail', models.CharField(max_length=400)),
                ('reason', models.TextField()),
                ('overridden_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('overridden_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='safety_overrides', to=settings.AUTH_USER_MODEL)),
                ('prescription_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_overrides', to='pharmacy.prescriptionitem')),
            ],
        ),
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=60)),
                ('expiry_date', models.DateField()),
                ('quantity_on_hand', models.IntegerField(default=0)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_batches', to='facilities.facility')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='pharmacy.medication')),
            ],
            options={
                'verbose_name_plural': 'stock batches',
                'ordering': ['expiry_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Dispense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('dispensed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('dispensed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispenses', to=settings.AUTH_USER_MODEL)),
                ('prescription_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispenses', to='pharmacy.prescriptionitem')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispenses', to='pharmacy.stockbatch')),
            ],
            options={
                'ordering': ['-dispensed_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('receipt', 'Goods received'), ('dispense', 'Dispensed'), ('adjustment', 'Adjustment'), ('return', 'Returned'), ('expiry_write_off', 'Written off, expired')], max_length=20)),
                ('quantity_delta', models.IntegerField(help_text='Negative for stock leaving.')),
                ('quantity_after', models.IntegerField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='pharmacy.stockbatch')),
                ('dispense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='pharmacy.dispense')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='medication',
            constraint=models.UniqueConstraint(fields=('generic_name', 'strength', 'dosage_form', 'brand_name'), name='medication_unique_presentation'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['patient', '-prescribed_at'], name='pharmacy_pr_patient_3f4c02_idx'),
        ),
        migrations.AddConstraint(
            model_name='prescriptionitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_dispensed__lte', models.F('quantity_prescribed'))), name='never_dispense_more_than_prescribed'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['medication', 'facility', 'expiry_date'], name='pharmacy_st_medicat_aeae79_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockbatch',
            constraint=models.UniqueConstraint(fields=('medication', 'facility', 'batch_number'), name='batch_unique_per_medication_and_facility'),
        ),
        migrations.AddConstraint(
            model_name='stockbatch',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_on_hand__gte', 0)), name='stock_never_negative'),
        ),
    ]
