# Generated by Django 6.1.1 on 2026-09-07 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price per dispensing unit, charged when medication is issued.', max_digits=10),
        ),
    ]
