# Generated by Django 6.1.1 on 2026-09-07 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0003_encounter_admission_vitalsigns_admission_and_more'),
        ('facilities', '0001_initial'),
        ('inpatient', '0001_initial'),
        ('patients', '0004_patient_patient_phone_trgm'),
        ('pharmacy', '0002_medication_selling_price'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['-prescribed_at'], 'permissions': [('dispense_medication', 'Can dispense medication'), ('override_safety_warning', 'Can prescribe despite a safety warning'), ('administer_medication', 'Can administer medication to an inpatient'), ('override_administration_warning', 'Can administer despite a safety warning')]},
        ),
        migrations.AddField(
            model_name='prescription',
            name='admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='inpatient.admission'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='is_discharge_medication',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='visits.visit'),
        ),
        migrations.AddConstraint(
            model_name='prescription',
            constraint=models.CheckConstraint(condition=models.Q(('visit__isnull', False), ('admission__isnull', False), _connector='OR'), name='prescription_belongs_to_a_visit_or_an_admission'),
        ),
    ]
